import { useCallback, useMemo, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import {
  Plus, Eye, Edit2, Trash2, X, Upload,
  AlertCircle, CheckCircle, Download, ChevronDown, CreditCard, FileDown, Loader2,
  MoreHorizontal, KeyRound, RotateCcw, UserCog,
} from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { admin as adminApi, students as studentsApi } from '../../api/endpoints';
import { useAdminPage, useListParams } from '../../hooks/useAdminPage';
import useScrollLock from '../../hooks/useScrollLock';
import { useDraft, useOnlineStatus } from '../../hooks/useDraft';
import DraftNotice from '../common/DraftNotice';
import Pagination from '../common/Pagination';
import RouteLoader from '../common/RouteLoader';
import FilterField from '../common/FilterField';
import { useRemoteSort, SortHeader } from '../common/SortableHeader';
import CredentialsDialog from './CredentialsDialog';
import { generateIDCards, generateStudentList } from '../../utils/pdfGenerator';

/*
 * The Students screen.
 *
 * WHAT CHANGED AND WHY
 * --------------------
 * 1. The list is served by GET /api/admin/students, one page at a time. It used
 *    to read a copy of all 2,013 students held in AuthContext and slice it in
 *    the browser — which meant no screen in the portal could render until that
 *    entire table had been downloaded.
 *
 * 2. The filter dropdowns are built from the `options` the API returns, which
 *    come from the programs/batches tables. They were hardcoded, and wrong:
 *    they offered "BS Artificial Intel." and "BS Cyber Security", which are not
 *    programmes this institute runs, and batches "2024"/"2023" when every real
 *    batch is named like "BSCS-2022". Choosing almost any filter matched
 *    nothing. Status offered "Inactive", which is not one of the six values the
 *    academic_status column allows.
 *
 * 3. Filtering, searching and paging all happen in SQL now, so they apply to
 *    every student rather than to whichever ones were in memory.
 *
 * 4. Add Student and Bulk Import write to the database. Both used to call
 *    setStudents([...students, ...]) and nothing else: the new rows lived in a
 *    React array, looked saved, and were gone on the next refresh.
 *
 * 5. Export pulls every student matching the CURRENT filters from
 *    /api/admin/students/export, so a roster is complete rather than being the
 *    25 rows on screen.
 *
 * 6. The row actions do what they say. The pencil opened the profile screen —
 *    the same thing the eye beside it did — so "edit" was decoration; it now
 *    opens a form that writes to PUT /api/students/:id. Status changes, a
 *    password reissue and a restore sit behind a menu, and a deleted student
 *    can be listed and brought back at all, which nothing in the portal could
 *    do before.
 */

// The six values students.academic_status actually allows.
const STATUSES = [
  'Active', 'Pending Verification', 'Suspended',
  'Withdrawn', 'Graduated', 'Alumni',
];

/*
 * The status changes offered directly from a row.
 *
 * Four of the six, because two are not a decision an administrator makes from a
 * list: "Pending Verification" is where an admission starts and moving a
 * student back into it means nothing, and "Alumni" follows from Graduated
 * rather than being chosen instead of it. Both remain settable in the edit
 * form, which is where a deliberate correction belongs.
 */
const STATUS_ACTIONS = [
  { value: 'Active', label: 'Mark as Active' },
  { value: 'Suspended', label: 'Suspend' },
  { value: 'Graduated', label: 'Mark as Graduated' },
  { value: 'Withdrawn', label: 'Withdraw' },
];

// Status pill colours. Withdrawn and Suspended are deliberately the same
// warning tone — both mean "not currently studying", and inventing a sixth
// colour to distinguish them adds noise, not information.
const STATUS_TONE = {
  Active: { bg: '#D1FAE5', fg: '#065F46' },
  Graduated: { bg: '#DBEAFE', fg: '#1E40AF' },
  Alumni: { bg: '#EDE9FE', fg: '#5B21B6' },
  'Pending Verification': { bg: '#FEF3C7', fg: '#92400E' },
  Suspended: { bg: '#FEE2E2', fg: '#991B1B' },
  Withdrawn: { bg: '#FEE2E2', fg: '#991B1B' },
};

// The fields the edit form writes. Only what the admin route accepts, and only
// what a person genuinely corrects from this screen — the registration number
// and the linked login are deliberately not among them.
const EDITABLE_FIELDS = [
  'first_name', 'last_name', 'phone', 'dob', 'gender',
  'program_id', 'batch_id', 'section_id', 'academic_status',
];

/*
 * The admission form.
 *
 * `registration_number` is NOT here any more: it is generated by the server.
 * The database holds three different hand-typed formats today —
 * `2023-AIMS-REG-0001` (2,000 rows), `2024-CS-001` and `FA22-BSE-100` — which
 * is what happens when every admission invents its own. Generating it also
 * removes the chance of two admissions claiming the same number.
 *
 * The parent block is part of the same form because admitting a student and
 * registering their guardian are one real-world act, and doing them separately
 * is why 2 of the 2,002 students in the database have no guardian at all.
 */
const EMPTY_STUDENT = {
  first_name: '',
  last_name: '',
  cnic_bform: '',
  program_id: '',
  batch_id: '',
  section_id: '',
  gender: '',
  phone: '',
  dob: '',
  address: '',

  // Guardian. Only the three marked fields are required, and only if any of
  // them is filled — a student can be admitted without one and linked later.
  parent_first_name: '',
  parent_last_name: '',
  parent_email: '',
  parent_phone: '',
  parent_relationship: 'Father',
};

export default function StudentsList() {
  const { viewStudentProfile } = useAuth();
  const online = useOnlineStatus();
  const [searchParams] = useSearchParams();

  // Filters can arrive in the URL (the dashboard's task list links here with
  // ?status=Pending+Verification), so the screen opens on the right cohort.
  const { params, filters, setFilter, setPage } = useListParams({
    q: '',
    program_id: searchParams.get('program_id') || '',
    batch_id: '',
    status: searchParams.get('status') || '',
    /*
     * '' lists live students; 'only' lists the soft-deleted ones.
     *
     * They are two views rather than one mixed list on purpose — a roster, a
     * count and an export must never quietly include people who have been
     * removed. The deleted view exists because a student can now be restored,
     * and a screen cannot offer to restore somebody it cannot list.
     */
    deleted: '',
    limit: 10,
  });

  const viewingDeleted = filters.deleted === 'only';

  /*
   * Column sorting. Sent to the API rather than applied here, because this list
   * is paged in SQL — sorting the ten rows on screen would reorder the page and
   * leave the other 1,993 students where they were. Re-ordering returns to page
   * one, or you land on page 7 of a list you have just re-ordered.
   */
  const { sort, toggle: toggleSort, params: sortParams } = useRemoteSort(null, () => setPage(1));

  const request = useMemo(() => ({ ...params, ...sortParams }), [params, sortParams]);

  const { data, loading, error, refresh } = useAdminPage(
    (p) => adminApi.students(p),
    request, { key: 'students', debounceMs: 300 });

  const rows = data?.rows ?? [];
  const pagination = data?.pagination ?? { page: 1, pages: 1, total: 0, limit: 10 };
  const options = data?.options ?? { programs: [], batches: [], sections: [] };

  // Only the batches belonging to the chosen programme are offerable.
  const batchesForProgram = useMemo(() => {
    if (!filters.program_id) return options.batches;
    return options.batches.filter(
      (b) => String(b.program_id) === String(filters.program_id),
    );
  }, [options.batches, filters.program_id]);

  const [showPdfMenu, setShowPdfMenu] = useState(false);
  const [exporting, setExporting] = useState(null);
  const [banner, setBanner] = useState(null);

  const flash = useCallback((tone, text) => {
    setBanner({ tone, text });
    setTimeout(() => setBanner(null), 4000);
  }, []);

  // ── Export ───────────────────────────────────────────────────────────────
  /*
   * Pulls every student the current filters match, then hands them to the PDF
   * builders. This is the only bulk request the admin portal makes, and it is
   * made on an explicit click rather than on every page load.
   */
  const runExport = async (kind) => {
    setShowPdfMenu(false);
    setExporting(kind);

    try {
      const { rows: all, count, truncated } = await adminApi.exportStudents({
        q: filters.q,
        program_id: filters.program_id,
        batch_id: filters.batch_id,
        status: filters.status,
        // Carried so an export always contains the rows on screen. Without it,
        // exporting from the deleted view would quietly produce a roster of
        // live students instead.
        deleted: filters.deleted,
      });

      if (!count) {
        flash('error', 'No students match the current filters.');
        return;
      }

      if (kind === 'id-cards') generateIDCards(all);
      else generateStudentList(all);

      flash(
        'success',
        `Exported ${count.toLocaleString()} student${count === 1 ? '' : 's'}`
        + (truncated ? ' (capped at 10,000 — narrow the filters for the rest)' : ''),
      );
    } catch (err) {
      flash('error', `Export failed: ${err.message}`);
    } finally {
      setExporting(null);
    }
  };

  // ── Add student ──────────────────────────────────────────────────────────
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [newStudent, setNewStudent] = useState(EMPTY_STUDENT);
  const [saving, setSaving] = useState(false);
  const [formError, setFormError] = useState('');

  /*
   * The half-typed form survives a refresh, a crash or a flat battery. It is
   * only saved once something has actually been entered, so merely opening the
   * modal does not leave a draft behind.
   */
  const draft = useDraft('admin.student.new', newStudent, {
    enabled: isAddModalOpen,
    onRestore: setNewStudent,
    /*
     * `parent_relationship` starts at "Father", so a plain "every value is
     * falsy" test would never see this form as empty and would leave a draft
     * behind for anyone who merely opened the dialog. Compare against the
     * initial shape instead: untouched means untouched.
     */
    isEmpty: (value) => Object.keys(EMPTY_STUDENT)
      .every((key) => (value[key] ?? '') === EMPTY_STUDENT[key]),
  });

  // The one-time credentials popup shown after a successful admission.
  const [credentials, setCredentials] = useState(null);

  const submitStudent = async (e) => {
    e.preventDefault();
    setFormError('');

    /*
     * Tested against the trimmed value, not the raw one. A field holding only
     * spaces is empty as far as the record is concerned — the API client trims
     * the payload on the way out and the server trims it again on the way in,
     * so " " would arrive as "" and come back as a server-side "Missing
     * required fields". Catching it here keeps the complaint next to the field.
     */
    const required = ['first_name', 'last_name', 'cnic_bform', 'program_id', 'batch_id'];
    const missing = required.filter((field) => !String(newStudent[field] ?? '').trim());
    if (missing.length) {
      setFormError(`Required: ${missing.join(', ').replace(/_/g, ' ')}`);
      return;
    }

    // A guardian is optional, but a half-filled one is a mistake. Catch it here
    // rather than letting the server reject the whole admission.
    const filled = (field) => Boolean(String(newStudent[field] ?? '').trim());
    const anyParent = filled('parent_first_name') || filled('parent_last_name')
      || filled('parent_email');
    if (anyParent && !(filled('parent_first_name') && filled('parent_last_name') && filled('parent_email'))) {
      setFormError("A guardian needs a first name, last name and email — or leave the whole section blank.");
      return;
    }

    setSaving(true);
    try {
      const result = await adminApi.admitStudent({
        first_name: newStudent.first_name,
        last_name: newStudent.last_name,
        cnic_bform: newStudent.cnic_bform,
        program_id: Number(newStudent.program_id),
        batch_id: Number(newStudent.batch_id),
        section_id: newStudent.section_id ? Number(newStudent.section_id) : undefined,
        gender: newStudent.gender || undefined,
        phone: newStudent.phone || undefined,
        dob: newStudent.dob || undefined,
        address: newStudent.address || undefined,
        parent: anyParent ? {
          first_name: newStudent.parent_first_name,
          last_name: newStudent.parent_last_name,
          email: newStudent.parent_email,
          phone: newStudent.parent_phone || undefined,
          relationship: newStudent.parent_relationship,
        } : undefined,
      });

      // The draft is only discarded once the database has the rows.
      draft.clear();
      setNewStudent(EMPTY_STUDENT);
      setIsAddModalOpen(false);

      // Straight into the credentials popup — this is the only moment those
      // passwords exist in readable form.
      setCredentials(result);
      refresh();

    } catch (err) {
      // The draft is deliberately left in place so nothing typed is lost.
      setFormError(err.message);
    } finally {
      setSaving(false);
    }
  };

  // ── Delete ───────────────────────────────────────────────────────────────
  const [confirmDelete, setConfirmDelete] = useState(null);

  const removeStudent = async () => {
    const target = confirmDelete;
    setConfirmDelete(null);
    try {
      await studentsApi.remove(target.id);
      flash('success', `${target.name} was removed.`);
      refresh();
    } catch (err) {
      flash('error', `Could not remove ${target.name}: ${err.message}`);
    }
  };

  // ── Row actions ──────────────────────────────────────────────────────────
  /*
   * Which row's overflow menu is open, by student id. Held here rather than in
   * each row so opening one closes any other — two menus open at once over a
   * table is how a click lands on the wrong student.
   */
  const [openMenu, setOpenMenu] = useState(null);

  // The row a write is in flight for, so its menu can show it is working and
  // a second click cannot fire the same action twice.
  const [busyId, setBusyId] = useState(null);

  /*
   * Every row action funnels through here: it runs the call, reports the
   * outcome in the banner and refetches the page.
   *
   * The refetch is what makes the table honest. A local state update would show
   * the new status instantly and be wrong the moment the server disagreed — and
   * the whole point of this screen's rewrite was that what it shows is what the
   * database holds.
   */
  const runAction = async (student, { label, run, success }) => {
    setOpenMenu(null);
    setBusyId(student.id);
    try {
      const result = await run();
      flash('success', success(student));
      refresh();
      return result;
    } catch (err) {
      flash('error', `${label} failed for ${student.name}: ${err.message}`);
      return null;
    } finally {
      setBusyId(null);
    }
  };

  const changeStatus = (student, status) => runAction(student, {
    label: 'Status change',
    run: () => studentsApi.update(student.id, { academic_status: status }),
    success: (s) => `${s.name} is now ${status}.`,
  });

  const restoreStudent = (student) => runAction(student, {
    label: 'Restore',
    run: () => studentsApi.restore(student.id),
    success: (s) => `${s.name} was restored. Their status is still ${s.status}.`,
  });

  /*
   * Issues a NEW password and shows it once.
   *
   * The old one cannot be retrieved — it is a bcrypt hash — so this replaces
   * it. That is why the confirmation below exists: doing this to the wrong
   * student locks them out of an account that was working, and the only remedy
   * is to hand them the new password.
   */
  const [confirmReissue, setConfirmReissue] = useState(null);

  const reissueCredentials = async () => {
    const student = confirmReissue;
    setConfirmReissue(null);

    const result = await runAction(student, {
      label: 'Password reissue',
      run: () => adminApi.reissueCredentials(student.userId),
      success: (s) => `A new password was issued for ${s.name}.`,
    });

    /*
     * Reissue answers with a flat { credentials } — CredentialsDialog expects
     * the provisioning shape, so it is mapped here. `name` comes from the row
     * because the endpoint returns the login, not the person.
     */
    if (result?.credentials) {
      setCredentials({
        student: {
          name: student.name,
          registrationNumber: student.regNo,
          email: result.credentials.email,
          password: result.credentials.password,
        },
      });
    }
  };

  // ── Edit ─────────────────────────────────────────────────────────────────
  /*
   * The pencil opens this form rather than navigating to the profile screen.
   *
   * Both buttons used to call viewStudentProfile(), so "edit" and "view" did
   * exactly the same thing — the pencil was decoration, and its tooltip
   * ("Edit on the student's profile") was an apology for that.
   *
   * The row already carries every field this form binds, so opening it costs no
   * request; only saving talks to the server.
   */
  const [editing, setEditing] = useState(null);
  const [editForm, setEditForm] = useState({});
  const [editError, setEditError] = useState('');
  const [savingEdit, setSavingEdit] = useState(false);

  /*
   * An unsaved edit survives a refresh or an accidental dismissal.
   *
   * The "Add a student" form beside this one has been drafted since drafts were
   * introduced; this one was not, even though it binds nine fields and closes
   * on a backdrop click. Verified on screen before this change: typing into it
   * wrote no draft key.
   *
   * PER-RECORD KEY. `admin.student.edit.5512` can only ever be offered back on
   * student 5512. A single shared key would restore one student's edits onto
   * another's record — a silent data corruption, not an inconvenience, because
   * saveEdit diffs against the row and would send them as real changes.
   *
   * This is the shape AnnouncementsView already uses for editing an existing
   * record; it is now the pattern for edits generally.
   */
  const editDraft = useDraft(
    `admin.student.edit.${editing?.id ?? 'none'}`,
    editForm,
    {
      enabled: !!editing,
      onRestore: setEditForm,
      /*
       * openEditor seeds this form from the row, so it is NEVER empty in the
       * literal sense — every field arrives populated. Emptiness here means
       * "unchanged", judged against the record the editor was opened on, so
       * simply opening the dialog and closing it leaves nothing behind.
       */
      isEmpty: (value) => {
        if (!editing || !value) return true;
        const baseline = {
          first_name: editing.firstName ?? '',
          last_name: editing.lastName ?? '',
          phone: editing.phone ?? '',
          dob: editing.dob ?? '',
          gender: editing.gender
            ? editing.gender.charAt(0).toUpperCase() + editing.gender.slice(1)
            : '',
          program_id: editing.programId ?? '',
          batch_id: editing.batchId ?? '',
          section_id: editing.sectionId ?? '',
          academic_status: editing.status ?? '',
        };
        return Object.keys(baseline).every(
          (k) => String(value[k] ?? '').trim() === String(baseline[k] ?? '').trim(),
        );
      },
    },
  );

  const openEditor = (student) => {
    setOpenMenu(null);
    setEditError('');
    setEditing(student);
    setEditForm({
      first_name: student.firstName ?? '',
      last_name: student.lastName ?? '',
      phone: student.phone ?? '',
      dob: student.dob ?? '',
      // The API stores Male/Female/Other; the list lowercases it for display.
      gender: student.gender
        ? student.gender.charAt(0).toUpperCase() + student.gender.slice(1)
        : '',
      program_id: student.programId ?? '',
      batch_id: student.batchId ?? '',
      section_id: student.sectionId ?? '',
      academic_status: student.status ?? '',
    });
  };

  const saveEdit = async (e) => {
    e.preventDefault();
    setEditError('');

    if (!editForm.first_name?.trim() || !editForm.last_name?.trim()) {
      setEditError('A student needs a first and last name.');
      return;
    }

    /*
     * Only what actually changed is sent.
     *
     * The route applies exactly the keys it receives, so a narrow payload is
     * also a narrow audit entry — "phone changed" rather than nine fields
     * rewritten to the values they already had, which is the difference between
     * a trail that can be read and one that cannot.
     */
    const changes = {};
    for (const field of EDITABLE_FIELDS) {
      const next = editForm[field];
      const before = {
        first_name: editing.firstName ?? '',
        last_name: editing.lastName ?? '',
        phone: editing.phone ?? '',
        dob: editing.dob ?? '',
        gender: editing.gender
          ? editing.gender.charAt(0).toUpperCase() + editing.gender.slice(1)
          : '',
        program_id: editing.programId ?? '',
        batch_id: editing.batchId ?? '',
        section_id: editing.sectionId ?? '',
        academic_status: editing.status ?? '',
      }[field];

      /*
       * Compared trimmed on both sides. The API client edge-trims the payload,
       * so adding a trailing space to a name and saving would otherwise count
       * as a change, send a value identical to the stored one, and write an
       * audit entry recording an edit that did not happen.
       */
      if (String(next ?? '').trim() !== String(before ?? '').trim()) {
        // The three id fields must reach the server as numbers, and an id
        // cleared to "" means "no section", which is null rather than 0.
        changes[field] = ['program_id', 'batch_id', 'section_id'].includes(field)
          ? (next === '' ? null : Number(next))
          : next;
      }
    }

    if (!Object.keys(changes).length) {
      // Nothing actually differs from the stored row, so there is no work to
      // protect — drop the draft rather than leave one that restores a form
      // identical to the record.
      editDraft.clear();
      setEditing(null);
      return;
    }

    setSavingEdit(true);
    try {
      await studentsApi.update(editing.id, changes);
      flash('success', `${editForm.first_name} ${editForm.last_name} was updated.`);
      // Only once the update has landed. A rejected save keeps the draft, which
      // is exactly when it is worth having.
      editDraft.clear();
      setEditing(null);
      refresh();
    } catch (err) {
      setEditError(err.message);
    } finally {
      setSavingEdit(false);
    }
  };

  // Batches and sections offered in the editor follow the programme and batch
  // chosen IN THE FORM, not the ones the student currently has — otherwise
  // moving a student to another programme offers only their old programme's
  // batches.
  const editBatches = useMemo(
    () => options.batches.filter(
      (b) => !editForm.program_id || String(b.program_id) === String(editForm.program_id),
    ),
    [options.batches, editForm.program_id],
  );

  const editSections = useMemo(
    () => options.sections.filter(
      (s) => !editForm.batch_id || String(s.batch_id) === String(editForm.batch_id),
    ),
    [options.sections, editForm.batch_id],
  );

  // ── Bulk import ──────────────────────────────────────────────────────────
  const [showBulkModal, setShowBulkModal] = useState(false);
  const [bulkText, setBulkText] = useState('');
  const [parsed, setParsed] = useState([]);
  const [bulkError, setBulkError] = useState('');
  const [importing, setImporting] = useState(false);
  const [importReport, setImportReport] = useState(null);
  const fileInputRef = useRef(null);

  const bulkDraft = useDraft('admin.student.bulk', bulkText, {
    enabled: showBulkModal,
    onRestore: (value) => { setBulkText(value); parseRows(value); },
    isEmpty: (value) => !value || !value.trim(),
  });

  /*
   * Freeze the roster behind any of the four dialogs.
   *
   * This screen is the worst case for the bug: the table is 2,000 students
   * long, so a wheel gesture over an open form scrolls the page a very long way
   * and there is no landmark to find the way back from. CredentialsDialog locks
   * itself, so it is not in this list.
   */
  useScrollLock(
    isAddModalOpen || !!confirmDelete || showBulkModal
    || !!editing || !!confirmReissue,
  );

  /*
   * Expects: registration_number, first_name, last_name, cnic_bform,
   * program, batch  — programme and batch given by NAME and resolved against
   * the real lookup tables, so a typo is caught here rather than becoming a
   * row pointing at the wrong programme.
   */
  function parseRows(text) {
    const lines = String(text || '').trim().split('\n').filter((l) => l.trim());
    if (lines.length < 2) {
      setBulkError('Provide a header row plus at least one student.');
      setParsed([]);
      return;
    }

    const delimiter = lines[1].includes('\t') ? '\t' : ',';
    const out = [];
    const errors = [];

    for (let i = 1; i < lines.length; i += 1) {
      /*
       * Trimmed on BOTH sides of the unquoting, not just before it. Stripping
       * the quotes second left the padding inside them untouched, so a cell
       * written "  Ali  " — which is exactly how a spreadsheet exports a name
       * someone typed with stray spaces — parsed to "  Ali  " and was admitted
       * under that name.
       */
      const cells = lines[i]
        .split(delimiter)
        .map((c) => c.trim().replace(/^"|"$/g, '').trim());
      const [regNo, first, last, cnic, programName, batchName] = cells;

      if (!regNo || !first || !last || !cnic) {
        errors.push(`Line ${i + 1}: registration number, first name, last name and CNIC are all required`);
        continue;
      }

      const program = options.programs.find(
        (p) => p.program_name.toLowerCase() === String(programName || '').toLowerCase(),
      );
      if (!program) {
        errors.push(`Line ${i + 1}: unknown programme "${programName}"`);
        continue;
      }

      const batch = options.batches.find(
        (b) => b.batch_name.toLowerCase() === String(batchName || '').toLowerCase()
          && b.program_id === program.program_id,
      );
      if (!batch) {
        errors.push(`Line ${i + 1}: unknown batch "${batchName}" for ${program.program_name}`);
        continue;
      }

      out.push({
        registration_number: regNo,
        first_name: first,
        last_name: last,
        cnic_bform: cnic,
        program_id: program.program_id,
        batch_id: batch.batch_id,
        _label: `${first} ${last}`,
      });
    }

    setBulkError(
      errors.length
        ? `${errors.length} row(s) rejected:\n${errors.slice(0, 5).join('\n')}${errors.length > 5 ? `\n…and ${errors.length - 5} more` : ''}`
        : '',
    );
    setParsed(out);
  }

  const handleFileUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      setBulkText(event.target.result);
      parseRows(event.target.result);
    };
    reader.readAsText(file);
  };

  /*
   * Rows are posted one at a time and the outcome of each is reported. A row
   * that the server rejects — a duplicate registration number, say — no longer
   * silently joins the others in a local array pretending to be saved.
   *
   * ADMIT, NOT REGISTER.
   *
   * This used to post to /api/students/register, which writes a `students` row
   * and nothing else. Every student brought in through bulk import therefore
   * had NO login: they could not sign in, no password existed to give them, and
   * nothing on any screen said so. A cohort imported from a spreadsheet was a
   * cohort locked out of the portal.
   *
   * /api/admin/students/admit creates the login alongside the record in one
   * transaction and returns the password exactly once — the same path the
   * single-admission form uses, so an imported student and an individually
   * admitted one end up identical. The CSV's own registration number is passed
   * through and honoured rather than regenerated.
   *
   * Those one-time passwords are collected and shown together at the end. They
   * cannot be read back afterwards, so losing them means reissuing every one.
   */
  const runImport = async () => {
    if (!parsed.length) return;
    setImporting(true);

    const failures = [];
    const issued = [];

    for (const row of parsed) {
      const { _label, ...payload } = row;
      try {
        const res = await adminApi.admitStudent(payload);
        issued.push({
          name: res?.student?.name || _label,
          regNo: res?.student?.registrationNumber || payload.registration_number,
          email: res?.student?.email,
          password: res?.credentials?.student?.password ?? res?.student?.password,
        });
      } catch (err) {
        failures.push(`${_label}: ${err.message}`);
      }
    }

    setImporting(false);
    setImportReport({ saved: issued.length, failures, issued });

    if (issued.length > 0) refresh();
    // The draft survives a partial import, so the rows that failed can be
    // corrected and retried rather than retyped.
    if (!failures.length) {
      bulkDraft.clear();
      setBulkText('');
      setParsed([]);
    }
  };

  /*
   * A CSV template, generated from THIS database.
   *
   * The importer matches programme and batch by name against the live lookup
   * tables, so a template with invented example values would fail on its own
   * sample row. The example below uses a real programme and one of its real
   * batches, which makes the file both a format guide and a working test.
   */
  const downloadTemplate = () => {
    const header = 'registration_number,first_name,last_name,cnic_bform,program,batch';
    const program = options.programs[0];
    const batch = program
      ? options.batches.find((b) => b.program_id === program.program_id)
      : null;

    const example = program && batch
      ? `2026-AIMS-REG-9001,Ayesha,Khan,3520112345671,"${program.program_name}","${batch.batch_name}"`
      : '2026-AIMS-REG-9001,Ayesha,Khan,3520112345671,<programme name>,<batch name>';

    const blob = new Blob([`${header}\n${example}\n`], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'student-import-template.csv';
    link.click();
    URL.revokeObjectURL(url);
  };

  // ── Rendering ────────────────────────────────────────────────────────────
  const selectStyle = {
    padding: '0.5rem 0.85rem', borderRadius: '8px', border: '1px solid #CBD5E1',
    fontSize: '0.85rem', outline: 'none', backgroundColor: '#FFFFFF',
    color: '#334155', fontWeight: 500, cursor: 'pointer', fontFamily: "'Inter', sans-serif",
  };

  const inputStyle = {
    width: '100%', padding: '0.5rem 0.7rem', borderRadius: '8px',
    border: '1px solid #CBD5E1', fontSize: '0.85rem', outline: 'none',
    boxSizing: 'border-box', fontFamily: "'Inter', sans-serif",
  };

  const labelStyle = { fontSize: '0.78rem', fontWeight: 600, color: '#475569' };

  // ── Row-action chrome ────────────────────────────────────────────────────
  const iconButtonStyle = (color) => ({
    background: 'none', border: 'none', color, cursor: 'pointer',
    padding: '5px', borderRadius: '6px', display: 'flex', alignItems: 'center',
  });

  const menuHeadingStyle = {
    margin: 0, padding: '0.4rem 0.85rem 0.25rem', fontSize: '0.65rem',
    fontWeight: 700, letterSpacing: '0.07em', textTransform: 'uppercase',
    color: '#94A3B8',
  };

  const menuItemStyle = (disabled = false) => ({
    display: 'flex', alignItems: 'center', gap: '9px', width: '100%',
    padding: '0.5rem 0.85rem', border: 'none', background: 'none',
    cursor: disabled ? 'not-allowed' : 'pointer', fontSize: '0.8rem',
    color: disabled ? '#CBD5E1' : '#0F172A', fontFamily: 'inherit',
    textAlign: 'left', opacity: disabled ? 0.6 : 1,
  });

  const menuDividerStyle = { height: '1px', backgroundColor: '#F1F5F9', margin: '0.25rem 0' };

  /*
   * The first load owns the whole screen.
   *
   * Before this, the filter bar, the table header and the footer reading
   * "Showing 0–0 of 0 students" all rendered while the request was in flight,
   * with a small spinner floated over the empty table body. "0 students" is
   * indistinguishable from a filter that matched nothing, which is exactly the
   * conclusion an admin draws from it.
   *
   * Refetches — typing in the search box, changing a filter, turning a page —
   * deliberately do NOT come back here. Those keep the current rows visible and
   * use the overlay spinner below, because a search box that blanks the page on
   * every keystroke cannot be typed into.
   */
  if (loading && !data) {
    return <RouteLoader label="Loading students…" hint="Roster, programmes and batches" />;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
      {/* Title & actions */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h2 style={{
            fontSize: '1.65rem', fontWeight: 800, color: '#0F172A',
            letterSpacing: '-0.02em', lineHeight: 1.1,
            fontFamily: "'Outfit', sans-serif", margin: 0,
          }}>
            Students
          </h2>
          <span style={{ fontSize: '0.8rem', color: '#64748B', fontWeight: 500 }}>
            Home / <span style={{ color: '#94A3B8' }}>Students</span>
          </span>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <div style={{ position: 'relative' }}>
            <button
              onClick={() => setShowPdfMenu(!showPdfMenu)}
              disabled={!!exporting}
              style={{
                backgroundColor: 'white', color: '#059669', fontWeight: 700,
                border: '2px solid #059669', borderRadius: '8px',
                padding: '0.6rem 1.2rem', fontSize: '0.875rem',
                cursor: exporting ? 'wait' : 'pointer',
                display: 'flex', alignItems: 'center', gap: '6px',
              }}
            >
              {exporting
                ? <Loader2 size={16} className="loader-spin" />
                : <Download size={16} />}
              PDF
              <ChevronDown size={12} />
            </button>

            {showPdfMenu && (
              <>
                <div style={{ position: 'fixed', inset: 0, zIndex: 50 }} onClick={() => setShowPdfMenu(false)} />
                <div style={{
                  position: 'absolute', right: 0, top: '100%', marginTop: '4px',
                  backgroundColor: 'white', borderRadius: '12px',
                  boxShadow: '0 10px 25px rgba(0,0,0,0.1)',
                  border: '1px solid #E2E8F0', zIndex: 51, width: '230px', overflow: 'hidden',
                }}>
                  <button
                    onClick={() => runExport('id-cards')}
                    style={{
                      display: 'flex', alignItems: 'center', gap: '10px', width: '100%',
                      padding: '0.65rem 1rem', border: 'none', background: 'none',
                      cursor: 'pointer', fontSize: '0.82rem', color: '#0F172A',
                    }}
                  >
                    <CreditCard size={16} color="#6366F1" />
                    <span style={{ textAlign: 'left' }}>
                      <strong style={{ display: 'block', fontSize: '0.82rem' }}>ID Cards</strong>
                      <span style={{ fontSize: '0.65rem', color: '#94A3B8' }}>
                        Every student matching these filters
                      </span>
                    </span>
                  </button>
                  <div style={{ height: '1px', backgroundColor: '#F1F5F9' }} />
                  <button
                    onClick={() => runExport('list')}
                    style={{
                      display: 'flex', alignItems: 'center', gap: '10px', width: '100%',
                      padding: '0.65rem 1rem', border: 'none', background: 'none',
                      cursor: 'pointer', fontSize: '0.82rem', color: '#0F172A',
                    }}
                  >
                    <FileDown size={16} color="#059669" />
                    <span style={{ textAlign: 'left' }}>
                      <strong style={{ display: 'block', fontSize: '0.82rem' }}>Student List</strong>
                      <span style={{ fontSize: '0.65rem', color: '#94A3B8' }}>
                        Full roster with contact details
                      </span>
                    </span>
                  </button>
                </div>
              </>
            )}
          </div>

          <button
            onClick={() => setShowBulkModal(true)}
            style={{
              backgroundColor: 'white', color: '#6366F1', fontWeight: 700,
              border: '2px solid #6366F1', borderRadius: '8px',
              padding: '0.6rem 1.2rem', fontSize: '0.875rem', cursor: 'pointer',
              display: 'flex', alignItems: 'center', gap: '6px',
            }}
          >
            <Upload size={16} /> Bulk Import
          </button>

          <button
            onClick={() => setIsAddModalOpen(true)}
            style={{
              backgroundColor: '#991b1b', color: 'white', fontWeight: 700,
              border: 'none', borderRadius: '8px', padding: '0.6rem 1.2rem',
              fontSize: '0.875rem', cursor: 'pointer',
              display: 'flex', alignItems: 'center', gap: '6px',
              boxShadow: '0 4px 12px rgba(220,38,38,0.3)',
            }}
          >
            <Plus size={16} /> Add Student
          </button>
        </div>
      </div>

      {banner && (
        <div style={{
          padding: '0.7rem 1rem', borderRadius: '10px', fontSize: '0.85rem',
          display: 'flex', alignItems: 'center', gap: '0.5rem',
          backgroundColor: banner.tone === 'success' ? '#ECFDF5' : '#FEF2F2',
          border: `1px solid ${banner.tone === 'success' ? '#A7F3D0' : '#FECACA'}`,
          color: banner.tone === 'success' ? '#065F46' : '#991B1B',
        }}>
          {banner.tone === 'success' ? <CheckCircle size={15} /> : <AlertCircle size={15} />}
          {banner.text}
        </div>
      )}

      {/* Main card */}
      <div style={{
        backgroundColor: '#FFFFFF', borderRadius: '16px', border: '1px solid #E2E8F0',
        padding: '1.25rem', boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
        display: 'flex', flexDirection: 'column', gap: '1.25rem',
      }}>
        {/* Filters — every option below is a real row from the database */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.85rem', flexWrap: 'wrap' }}>
          <FilterField
            value={filters.q}
            onChange={(value) => setFilter('q', value)}
            placeholder="Search by student name, registration number, email or phone…"
            style={{ flex: '1 1 240px' }}
            inputStyle={{ ...inputStyle, padding: '0.5rem 2.2rem' }}
          />

          <select
            value={filters.program_id}
            onChange={(e) => { setFilter('program_id', e.target.value); setFilter('batch_id', ''); }}
            style={selectStyle}
          >
            <option value="">All Programs</option>
            {options.programs.map((p) => (
              <option key={p.program_id} value={p.program_id}>{p.program_name}</option>
            ))}
          </select>

          <select value={filters.batch_id} onChange={(e) => setFilter('batch_id', e.target.value)} style={selectStyle}>
            <option value="">All Batches</option>
            {batchesForProgram.map((b) => (
              <option key={b.batch_id} value={b.batch_id}>{b.batch_name}</option>
            ))}
          </select>

          <select value={filters.status} onChange={(e) => setFilter('status', e.target.value)} style={selectStyle}>
            <option value="">All Status</option>
            {STATUSES.map((s) => <option key={s} value={s}>{s}</option>)}
          </select>

          {/* Current or deleted records. A separate control from Status
              because "deleted" is not an academic status — a deleted student
              still has one, and that is what they come back as. */}
          <select
            value={filters.deleted}
            onChange={(e) => setFilter('deleted', e.target.value)}
            style={{
              ...selectStyle,
              ...(viewingDeleted
                ? { borderColor: '#FECACA', backgroundColor: '#FEF2F2', color: '#991B1B', fontWeight: 700 }
                : null),
            }}
          >
            <option value="">Current records</option>
            <option value="only">Deleted records</option>
          </select>
        </div>

        {viewingDeleted && (
          <div style={{
            padding: '0.7rem 1rem', borderRadius: '10px', fontSize: '0.82rem',
            backgroundColor: '#FEF2F2', border: '1px solid #FECACA', color: '#991B1B',
            display: 'flex', alignItems: 'center', gap: '0.5rem',
          }}>
            <AlertCircle size={15} style={{ flexShrink: 0 }} />
            Showing students who have been removed. Their attendance, marks and
            fee history are intact — restoring one brings the record back with
            the status it had when it was removed.
          </div>
        )}

        {error && (
          <div style={{
            padding: '1rem', borderRadius: '10px', backgroundColor: '#FEF2F2',
            border: '1px solid #FECACA', color: '#991B1B', fontSize: '0.85rem',
          }}>
            <strong>Could not load students.</strong> {error}{' '}
            <button onClick={refresh} style={{ marginLeft: 8, border: '1px solid #FECACA', background: 'white', borderRadius: 6, padding: '2px 8px', cursor: 'pointer', color: '#991B1B', fontWeight: 600 }}>
              Retry
            </button>
          </div>
        )}

        {/* Table.
            `overflow: auto` clips anything positioned outside the box, which
            would slice the bottom off a row's action menu — so the scroller is
            released while one is open. Nothing can be scrolled out of reach
            meanwhile: the menu closes on the next click either way. */}
        <div style={{
          overflowX: openMenu ? 'visible' : 'auto',
          position: 'relative',
        }}>
          {loading && (
            <div style={{
              position: 'absolute', inset: 0, backgroundColor: 'rgba(255,255,255,0.6)',
              display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 2,
            }}>
              <Loader2 size={22} className="loader-spin" color="#991b1b" />
            </div>
          )}

          <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
            <thead>
              <tr style={{ backgroundColor: '#F8FAFC', borderBottom: '1px solid #E2E8F0', fontSize: '0.75rem', color: '#64748B', fontWeight: 700 }}>
                {[
                  ['id', 'ID'], ['regNo', 'Reg. No.'], ['name', 'Name'],
                  ['program', 'Program'], ['batch', 'Batch'],
                  ['semester', 'Semester'], ['status', 'Status'],
                ].map(([key, label]) => (
                  <SortHeader
                    key={key}
                    label={label}
                    sortKey={key}
                    sort={sort}
                    onToggle={toggleSort}
                    style={{ padding: '0.85rem 1rem' }}
                  />
                ))}
                {/* Actions holds buttons, not a value — there is nothing to
                    order it by. */}
                <th style={{ padding: '0.85rem 1rem', textAlign: 'right' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {rows.length === 0 && !loading ? (
                <tr>
                  <td colSpan={8} style={{ padding: '3rem 1rem', textAlign: 'center', color: '#94A3B8', fontSize: '0.85rem' }}>
                    No students match these filters.
                  </td>
                </tr>
              ) : rows.map((student) => (
                <tr key={student.id} style={{ borderBottom: '1px solid #F1F5F9', fontSize: '0.875rem' }}>
                  <td style={{ padding: '0.85rem 1rem', color: '#64748B', fontWeight: 600 }}>{student.id}</td>
                  <td style={{ padding: '0.85rem 1rem', color: '#334155', fontWeight: 600 }}>{student.regNo}</td>
                  {/* Not clickable in the deleted view: the profile endpoint
                      only serves live students, so the link would open a
                      "student not found" screen. */}
                  <td
                    onClick={viewingDeleted ? undefined : () => viewStudentProfile(student.id)}
                    style={{
                      padding: '0.85rem 1rem', fontWeight: 700,
                      color: viewingDeleted ? '#94A3B8' : '#0F172A',
                      cursor: viewingDeleted ? 'default' : 'pointer',
                    }}
                    title={viewingDeleted ? 'Deleted record' : 'View student profile'}
                  >
                    {student.name}
                  </td>
                  <td style={{ padding: '0.85rem 1rem', color: '#475569' }}>{student.program || '—'}</td>
                  <td style={{ padding: '0.85rem 1rem', color: '#64748B' }}>{student.batch || '—'}</td>
                  <td style={{ padding: '0.85rem 1rem', color: '#64748B' }}>{student.semester || '—'}</td>
                  <td style={{ padding: '0.85rem 1rem' }}>
                    {(() => {
                      const tone = STATUS_TONE[student.status]
                        || { bg: '#F1F5F9', fg: '#475569' };
                      return (
                        <span style={{
                          backgroundColor: tone.bg, color: tone.fg,
                          fontSize: '0.7rem', fontWeight: 700, padding: '0.2rem 0.6rem',
                          borderRadius: '9999px', display: 'inline-block', whiteSpace: 'nowrap',
                        }}>
                          {student.status || '—'}
                        </span>
                      );
                    })()}
                  </td>
                  <td style={{ padding: '0.85rem 1rem' }}>
                    {/* Two direct buttons for the two things done constantly,
                        and everything consequential behind the menu — so
                        suspending a student or replacing their password is
                        never one stray click away from viewing them. */}
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: '0.15rem' }}>
                      {busyId === student.id && (
                        <Loader2 size={14} className="loader-spin" color="#991b1b" />
                      )}

                      {!viewingDeleted && (
                        <>
                          <button
                            onClick={() => viewStudentProfile(student.id)}
                            style={iconButtonStyle('#64748B')}
                            title="View profile"
                          >
                            <Eye size={16} />
                          </button>
                          <button
                            onClick={() => openEditor(student)}
                            style={iconButtonStyle('#334155')}
                            title="Edit this student"
                          >
                            <Edit2 size={16} />
                          </button>
                        </>
                      )}

                      {/* A deleted student has exactly one thing that can be
                          done to them, so it is offered directly rather than
                          hidden behind a menu of actions that do not apply. */}
                      {viewingDeleted ? (
                        <button
                          onClick={() => restoreStudent(student)}
                          disabled={busyId === student.id}
                          style={{
                            display: 'flex', alignItems: 'center', gap: '5px',
                            padding: '0.35rem 0.7rem', borderRadius: '8px',
                            border: '1px solid #A7F3D0', backgroundColor: '#ECFDF5',
                            color: '#065F46', fontWeight: 700, fontSize: '0.75rem',
                            cursor: busyId === student.id ? 'wait' : 'pointer',
                          }}
                        >
                          <RotateCcw size={13} /> Restore
                        </button>
                      ) : (
                        <div style={{ position: 'relative' }}>
                          <button
                            onClick={() => setOpenMenu(openMenu === student.id ? null : student.id)}
                            style={iconButtonStyle('#64748B')}
                            title="More actions"
                            aria-haspopup="menu"
                            aria-expanded={openMenu === student.id}
                          >
                            <MoreHorizontal size={16} />
                          </button>

                          {openMenu === student.id && (
                            <>
                              {/* Catches the click that dismisses the menu, so
                                  it never closes by losing focus mid-scroll. */}
                              <div
                                style={{ position: 'fixed', inset: 0, zIndex: 60 }}
                                onClick={() => setOpenMenu(null)}
                              />
                              <div
                                role="menu"
                                style={{
                                  position: 'absolute', right: 0, top: '100%', marginTop: '4px',
                                  minWidth: '212px', zIndex: 61, textAlign: 'left',
                                  backgroundColor: '#FFFFFF', borderRadius: '10px',
                                  border: '1px solid #E2E8F0',
                                  boxShadow: '0 10px 25px rgba(15,23,42,0.12)',
                                  overflow: 'hidden', padding: '0.3rem 0',
                                }}
                              >
                                <p style={menuHeadingStyle}>Status</p>
                                {STATUS_ACTIONS
                                  .filter((action) => action.value !== student.status)
                                  .map((action) => (
                                    <button
                                      key={action.value}
                                      role="menuitem"
                                      onClick={() => changeStatus(student, action.value)}
                                      style={menuItemStyle()}
                                    >
                                      <UserCog size={14} color="#64748B" />
                                      {action.label}
                                    </button>
                                  ))}

                                <div style={menuDividerStyle} />
                                <p style={menuHeadingStyle}>Account</p>

                                <button
                                  role="menuitem"
                                  onClick={() => { setOpenMenu(null); setConfirmReissue(student); }}
                                  disabled={!student.userId}
                                  title={student.userId
                                    ? undefined
                                    : 'This student has no login to reissue'}
                                  style={menuItemStyle(!student.userId)}
                                >
                                  <KeyRound size={14} color="#64748B" />
                                  Reissue password
                                </button>

                                <div style={menuDividerStyle} />

                                <button
                                  role="menuitem"
                                  onClick={() => { setOpenMenu(null); setConfirmDelete(student); }}
                                  style={{ ...menuItemStyle(), color: '#991B1B' }}
                                >
                                  <Trash2 size={14} color="#991B1B" />
                                  Remove student
                                </button>
                              </div>
                            </>
                          )}
                        </div>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Page numbers come from the server's row count, not from the rows on
            screen. Shared with every other list in the portal. */}
        <Pagination
          page={pagination.page}
          pages={pagination.pages}
          total={pagination.total}
          limit={pagination.limit}
          count={rows.length}
          onChange={setPage}
          noun="student"
          loading={loading}
        />
      </div>

      <style>{`
        .loader-spin { animation: spin 1s linear infinite; }
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
      `}</style>

      {/* ── Add Student ─────────────────────────────────────────────────── */}
      {isAddModalOpen && (
        <div
          style={{
            position: 'fixed', inset: 0, backgroundColor: 'rgba(15,23,42,0.6)',
            backdropFilter: 'blur(4px)', zIndex: 110, display: 'flex',
            alignItems: 'center', justifyContent: 'center', padding: '1rem',
          }}
          onClick={() => setIsAddModalOpen(false)}
        >
          <form
            onSubmit={submitStudent}
            onClick={(e) => e.stopPropagation()}
            style={{
              backgroundColor: 'white', borderRadius: '18px', width: '100%',
              maxWidth: '600px', border: '1px solid #E2E8F0', overflow: 'hidden',
              maxHeight: '90vh', display: 'flex', flexDirection: 'column',
            }}
          >
            <div style={{
              padding: '1.15rem 1.5rem', borderBottom: '1px solid #E2E8F0',
              display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            }}>
              <h3 style={{ fontSize: '1.1rem', fontWeight: 800, color: '#0F172A', margin: 0, fontFamily: "'Outfit', sans-serif" }}>
                Admit Student
              </h3>
              <button type="button" onClick={() => setIsAddModalOpen(false)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#64748B' }}>
                <X size={18} />
              </button>
            </div>

            <div style={{ padding: '1.25rem 1.5rem', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
              <DraftNotice draft={draft} online={online} onDiscard={() => setNewStudent(EMPTY_STUDENT)} />

              {formError && (
                <div style={{ padding: '0.6rem 0.85rem', borderRadius: '8px', backgroundColor: '#FEF2F2', border: '1px solid #FECACA', color: '#991B1B', fontSize: '0.8rem' }}>
                  {formError}
                </div>
              )}

              {/* The registration number, the student's email and both
                  passwords are generated by the server when this form is
                  submitted. Saying so up front stops an admin looking for
                  fields that are deliberately absent. */}
              <div style={{
                padding: '0.6rem 0.85rem', borderRadius: '8px',
                backgroundColor: '#EFF6FF', border: '1px solid #BFDBFE',
                color: '#1E40AF', fontSize: '0.78rem',
              }}>
                The registration number, the student's login and the guardian's
                login are created automatically. You will be shown the passwords
                once, straight after saving.
              </div>

              <p style={{
                fontSize: '0.7rem', fontWeight: 800, color: '#64748B', margin: '0.25rem 0 0',
                textTransform: 'uppercase', letterSpacing: '0.06em',
              }}>
                Student
              </p>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.85rem' }}>
                {[
                  ['first_name', 'First Name *', 'text'],
                  ['last_name', 'Last Name *', 'text'],
                  ['cnic_bform', 'CNIC / B-Form *', 'text'],
                  ['phone', 'Phone', 'text'],
                  ['dob', 'Date of Birth', 'date'],
                  ['address', 'Address', 'text'],
                ].map(([field, label, type]) => (
                  <label key={field} style={{ fontSize: '0.78rem', fontWeight: 600, color: '#475569' }}>
                    {label}
                    <input
                      type={type}
                      value={newStudent[field]}
                      onChange={(e) => setNewStudent({ ...newStudent, [field]: e.target.value })}
                      style={{ ...inputStyle, marginTop: '4px' }}
                    />
                  </label>
                ))}

                <label style={{ fontSize: '0.78rem', fontWeight: 600, color: '#475569' }}>
                  Program *
                  <select
                    value={newStudent.program_id}
                    onChange={(e) => setNewStudent({ ...newStudent, program_id: e.target.value, batch_id: '' })}
                    style={{ ...inputStyle, marginTop: '4px' }}
                  >
                    <option value="">Select…</option>
                    {options.programs.map((p) => (
                      <option key={p.program_id} value={p.program_id}>{p.program_name}</option>
                    ))}
                  </select>
                </label>

                <label style={{ fontSize: '0.78rem', fontWeight: 600, color: '#475569' }}>
                  Batch *
                  <select
                    value={newStudent.batch_id}
                    onChange={(e) => setNewStudent({ ...newStudent, batch_id: e.target.value })}
                    style={{ ...inputStyle, marginTop: '4px' }}
                  >
                    <option value="">Select…</option>
                    {options.batches
                      .filter((b) => !newStudent.program_id || String(b.program_id) === String(newStudent.program_id))
                      .map((b) => <option key={b.batch_id} value={b.batch_id}>{b.batch_name}</option>)}
                  </select>
                </label>

                <label style={{ fontSize: '0.78rem', fontWeight: 600, color: '#475569' }}>
                  Section
                  <select
                    value={newStudent.section_id}
                    onChange={(e) => setNewStudent({ ...newStudent, section_id: e.target.value })}
                    style={{ ...inputStyle, marginTop: '4px' }}
                  >
                    <option value="">Select…</option>
                    {options.sections
                      .filter((s) => !newStudent.batch_id || String(s.batch_id) === String(newStudent.batch_id))
                      .map((s) => <option key={s.section_id} value={s.section_id}>{s.section_name}</option>)}
                  </select>
                </label>

                <label style={{ fontSize: '0.78rem', fontWeight: 600, color: '#475569' }}>
                  Gender
                  <select
                    value={newStudent.gender}
                    onChange={(e) => setNewStudent({ ...newStudent, gender: e.target.value })}
                    style={{ ...inputStyle, marginTop: '4px' }}
                  >
                    <option value="">Select…</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    <option value="Other">Other</option>
                  </select>
                </label>
              </div>

              {/* ---- Guardian ----------------------------------------------
                  Collected here, with the student, because that is one real
                  act. Registering them on a separate screen afterwards is why
                  two students in this database have no guardian at all — and a
                  student with no linked parent means a parent portal with
                  nothing in it. */}
              <div style={{
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                marginTop: '0.5rem', paddingTop: '0.85rem', borderTop: '1px solid #E2E8F0',
              }}>
                <p style={{
                  fontSize: '0.7rem', fontWeight: 800, color: '#64748B', margin: 0,
                  textTransform: 'uppercase', letterSpacing: '0.06em',
                }}>
                  Parent / Guardian
                </p>
                <span style={{ fontSize: '0.7rem', color: '#94A3B8' }}>
                  Optional — but fill it now if you can
                </span>
              </div>

              <div style={{
                padding: '0.55rem 0.8rem', borderRadius: '8px',
                backgroundColor: '#F8FAFC', border: '1px solid #E2E8F0',
                color: '#475569', fontSize: '0.75rem',
              }}>
                Use the guardian's <strong>real email</strong> — it becomes their
                login. If it already belongs to a parent here, this student is
                added to that existing account and their current password keeps
                working. They can complete the rest of their details themselves
                from their own profile.
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.85rem' }}>
                {[
                  ['parent_first_name', 'Guardian First Name', 'text'],
                  ['parent_last_name', 'Guardian Last Name', 'text'],
                  ['parent_email', 'Guardian Email', 'email'],
                  ['parent_phone', 'Guardian Phone', 'text'],
                ].map(([field, label, type]) => (
                  <label key={field} style={{ fontSize: '0.78rem', fontWeight: 600, color: '#475569' }}>
                    {label}
                    <input
                      type={type}
                      value={newStudent[field]}
                      onChange={(e) => setNewStudent({ ...newStudent, [field]: e.target.value })}
                      style={{ ...inputStyle, marginTop: '4px' }}
                    />
                  </label>
                ))}

                <label style={{ fontSize: '0.78rem', fontWeight: 600, color: '#475569' }}>
                  Relationship
                  <select
                    value={newStudent.parent_relationship}
                    onChange={(e) => setNewStudent({ ...newStudent, parent_relationship: e.target.value })}
                    style={{ ...inputStyle, marginTop: '4px' }}
                  >
                    {/* The three values student_guardians.relationship allows. */}
                    <option value="Father">Father</option>
                    <option value="Mother">Mother</option>
                    <option value="Guardian">Guardian</option>
                  </select>
                </label>
              </div>
            </div>

            <div style={{
              padding: '1rem 1.5rem', borderTop: '1px solid #E2E8F0',
              display: 'flex', justifyContent: 'flex-end', gap: '0.6rem', backgroundColor: '#F8FAFC',
            }}>
              <button
                type="button"
                onClick={() => setIsAddModalOpen(false)}
                style={{ padding: '0.55rem 1.1rem', borderRadius: '8px', border: '1px solid #CBD5E1', background: 'white', color: '#475569', fontWeight: 600, cursor: 'pointer', fontSize: '0.85rem' }}
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={saving || !online}
                title={!online ? 'You are offline — your work is saved on this device' : undefined}
                style={{
                  padding: '0.55rem 1.1rem', borderRadius: '8px', border: 'none',
                  backgroundColor: saving || !online ? '#CBD5E1' : '#991b1b', color: 'white',
                  fontWeight: 700, cursor: saving || !online ? 'not-allowed' : 'pointer', fontSize: '0.85rem',
                  display: 'flex', alignItems: 'center', gap: '6px',
                }}
              >
                {saving && <Loader2 size={14} className="loader-spin" />}
                {saving ? 'Creating accounts…' : 'Admit & Create Accounts'}
              </button>
            </div>
          </form>
        </div>
      )}

      {/* ── Edit student ────────────────────────────────────────────────── */}
      {editing && (
        <div
          style={{
            position: 'fixed', inset: 0, backgroundColor: 'rgba(15,23,42,0.6)',
            backdropFilter: 'blur(4px)', zIndex: 115, display: 'flex',
            alignItems: 'center', justifyContent: 'center', padding: '1rem',
          }}
          onClick={() => !savingEdit && setEditing(null)}
        >
          <form
            onSubmit={saveEdit}
            onClick={(e) => e.stopPropagation()}
            style={{
              backgroundColor: 'white', borderRadius: '16px', width: '100%',
              maxWidth: '580px', border: '1px solid #E2E8F0', overflow: 'hidden',
              maxHeight: '90vh', display: 'flex', flexDirection: 'column',
            }}
          >
            <div style={{
              padding: '1.1rem 1.4rem', borderBottom: '1px solid #E2E8F0',
              display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1rem',
            }}>
              <div>
                <h3 style={{
                  fontSize: '1.05rem', fontWeight: 700, color: '#0F172A', margin: 0,
                  fontFamily: "'Outfit', sans-serif",
                }}>
                  Edit {editing.name}
                </h3>
                <p style={{ fontSize: '0.78rem', color: '#64748B', margin: '2px 0 0' }}>
                  {editing.regNo}
                </p>
              </div>
              <button
                type="button"
                onClick={() => setEditing(null)}
                aria-label="Close"
                style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#64748B', padding: 4 }}
              >
                <X size={18} />
              </button>
            </div>

            <div style={{
              padding: '1.2rem 1.4rem', overflowY: 'auto',
              display: 'flex', flexDirection: 'column', gap: '0.9rem',
            }}>
              {editError && (
                <div style={{
                  padding: '0.6rem 0.85rem', borderRadius: '8px',
                  backgroundColor: '#FEF2F2', border: '1px solid #FECACA',
                  color: '#991B1B', fontSize: '0.8rem',
                }}>
                  {editError}
                </div>
              )}

              <DraftNotice
                draft={editDraft}
                online={online}
                onDiscard={() => openEditor(editing)}
                compact
              />

              {/* Said plainly, because the two most obvious things to look for
                  in this form are the two things it deliberately does not
                  offer. */}
              <div style={{
                padding: '0.6rem 0.85rem', borderRadius: '8px',
                backgroundColor: '#F8FAFC', border: '1px solid #E2E8F0',
                color: '#475569', fontSize: '0.76rem',
              }}>
                The registration number and the linked login cannot be changed
                here. Every edit is recorded in the audit trail against your
                account.
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.9rem' }}>
                {[
                  ['first_name', 'First Name *', 'text'],
                  ['last_name', 'Last Name *', 'text'],
                  ['phone', 'Phone', 'text'],
                  ['dob', 'Date of Birth', 'date'],
                ].map(([field, label, type]) => (
                  <label key={field} style={labelStyle}>
                    {label}
                    <input
                      type={type}
                      value={editForm[field] ?? ''}
                      onChange={(e) => setEditForm({ ...editForm, [field]: e.target.value })}
                      style={{ ...inputStyle, marginTop: '4px' }}
                    />
                  </label>
                ))}

                <label style={labelStyle}>
                  Gender
                  <select
                    value={editForm.gender ?? ''}
                    onChange={(e) => setEditForm({ ...editForm, gender: e.target.value })}
                    style={{ ...inputStyle, marginTop: '4px' }}
                  >
                    <option value="">Not recorded</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    <option value="Other">Other</option>
                  </select>
                </label>

                <label style={labelStyle}>
                  Status
                  <select
                    value={editForm.academic_status ?? ''}
                    onChange={(e) => setEditForm({ ...editForm, academic_status: e.target.value })}
                    style={{ ...inputStyle, marginTop: '4px' }}
                  >
                    {STATUSES.map((s) => <option key={s} value={s}>{s}</option>)}
                  </select>
                </label>

                {/* Programme, batch and section cascade: changing one clears
                    the levels below it, because a batch from another programme
                    is not a valid placement and silently keeping it is how a
                    student ends up in a section they do not belong to. */}
                <label style={labelStyle}>
                  Program
                  <select
                    value={editForm.program_id ?? ''}
                    onChange={(e) => setEditForm({
                      ...editForm, program_id: e.target.value, batch_id: '', section_id: '',
                    })}
                    style={{ ...inputStyle, marginTop: '4px' }}
                  >
                    <option value="">Unassigned</option>
                    {options.programs.map((p) => (
                      <option key={p.program_id} value={p.program_id}>{p.program_name}</option>
                    ))}
                  </select>
                </label>

                <label style={labelStyle}>
                  Batch
                  <select
                    value={editForm.batch_id ?? ''}
                    onChange={(e) => setEditForm({
                      ...editForm, batch_id: e.target.value, section_id: '',
                    })}
                    style={{ ...inputStyle, marginTop: '4px' }}
                  >
                    <option value="">Unassigned</option>
                    {editBatches.map((b) => (
                      <option key={b.batch_id} value={b.batch_id}>{b.batch_name}</option>
                    ))}
                  </select>
                </label>

                <label style={labelStyle}>
                  Section
                  <select
                    value={editForm.section_id ?? ''}
                    onChange={(e) => setEditForm({ ...editForm, section_id: e.target.value })}
                    style={{ ...inputStyle, marginTop: '4px' }}
                  >
                    <option value="">Unassigned</option>
                    {editSections.map((s) => (
                      <option key={s.section_id} value={s.section_id}>{s.section_name}</option>
                    ))}
                  </select>
                </label>
              </div>
            </div>

            <div style={{
              padding: '0.9rem 1.4rem', borderTop: '1px solid #E2E8F0',
              display: 'flex', justifyContent: 'flex-end', gap: '0.6rem',
              backgroundColor: '#F8FAFC',
            }}>
              <button
                type="button"
                onClick={() => setEditing(null)}
                style={{
                  padding: '0.55rem 1.1rem', borderRadius: '8px',
                  border: '1px solid #CBD5E1', background: 'white', color: '#475569',
                  fontWeight: 600, cursor: 'pointer', fontSize: '0.85rem',
                }}
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={savingEdit || !online}
                title={!online ? 'You are offline' : undefined}
                style={{
                  padding: '0.55rem 1.1rem', borderRadius: '8px', border: 'none',
                  backgroundColor: savingEdit || !online ? '#CBD5E1' : '#991b1b',
                  color: 'white', fontWeight: 700, fontSize: '0.85rem',
                  cursor: savingEdit || !online ? 'not-allowed' : 'pointer',
                  display: 'flex', alignItems: 'center', gap: '6px',
                }}
              >
                {savingEdit && <Loader2 size={14} className="loader-spin" />}
                {savingEdit ? 'Saving…' : 'Save changes'}
              </button>
            </div>
          </form>
        </div>
      )}

      {/* ── Reissue confirmation ────────────────────────────────────────── */}
      {confirmReissue && (
        <div
          style={{
            position: 'fixed', inset: 0, backgroundColor: 'rgba(15,23,42,0.6)',
            backdropFilter: 'blur(4px)', zIndex: 120, display: 'flex',
            alignItems: 'center', justifyContent: 'center', padding: '1rem',
          }}
          onClick={() => setConfirmReissue(null)}
        >
          <div
            onClick={(e) => e.stopPropagation()}
            style={{
              backgroundColor: 'white', borderRadius: '14px', padding: '1.4rem',
              maxWidth: '440px', width: '100%',
            }}
          >
            <h3 style={{ margin: '0 0 0.5rem', fontSize: '1.02rem', fontWeight: 700, color: '#0F172A' }}>
              Issue a new password for {confirmReissue.name}?
            </h3>
            {/* The consequence, before the button rather than after it. */}
            <p style={{ fontSize: '0.85rem', color: '#64748B', margin: '0 0 1.2rem', lineHeight: 1.5 }}>
              Their current password stops working immediately. The new one is
              shown to you once and cannot be looked up again, so make sure you
              can hand it over now. This is recorded in the audit trail.
            </p>
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.6rem' }}>
              <button
                onClick={() => setConfirmReissue(null)}
                style={{
                  padding: '0.5rem 1rem', borderRadius: '8px', border: '1px solid #CBD5E1',
                  background: 'white', color: '#475569', fontWeight: 600,
                  cursor: 'pointer', fontSize: '0.85rem',
                }}
              >
                Cancel
              </button>
              <button
                onClick={reissueCredentials}
                style={{
                  padding: '0.5rem 1rem', borderRadius: '8px', border: 'none',
                  backgroundColor: '#991b1b', color: 'white', fontWeight: 700,
                  cursor: 'pointer', fontSize: '0.85rem',
                  display: 'flex', alignItems: 'center', gap: '6px',
                }}
              >
                <KeyRound size={14} /> Issue new password
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Delete confirmation ─────────────────────────────────────────── */}
      {confirmDelete && (
        <div
          style={{
            position: 'fixed', inset: 0, backgroundColor: 'rgba(15,23,42,0.6)',
            backdropFilter: 'blur(4px)', zIndex: 120, display: 'flex',
            alignItems: 'center', justifyContent: 'center', padding: '1rem',
          }}
          onClick={() => setConfirmDelete(null)}
        >
          <div
            onClick={(e) => e.stopPropagation()}
            style={{ backgroundColor: 'white', borderRadius: '16px', padding: '1.5rem', maxWidth: '420px', width: '100%' }}
          >
            <h3 style={{ margin: '0 0 0.5rem', fontSize: '1.05rem', fontWeight: 800, color: '#0F172A' }}>
              Remove {confirmDelete.name}?
            </h3>
            <p style={{ fontSize: '0.85rem', color: '#64748B', margin: '0 0 1.25rem', lineHeight: 1.5 }}>
              This marks {confirmDelete.regNo} as deleted in the database. Their
              attendance, marks and fee history are kept, and the record can be
              brought back from <strong>Deleted records</strong> in the filter
              bar if this was a mistake.
            </p>
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.6rem' }}>
              <button
                onClick={() => setConfirmDelete(null)}
                style={{ padding: '0.5rem 1rem', borderRadius: '8px', border: '1px solid #CBD5E1', background: 'white', color: '#475569', fontWeight: 600, cursor: 'pointer', fontSize: '0.85rem' }}
              >
                Cancel
              </button>
              <button
                onClick={removeStudent}
                style={{ padding: '0.5rem 1rem', borderRadius: '8px', border: 'none', backgroundColor: '#991b1b', color: 'white', fontWeight: 700, cursor: 'pointer', fontSize: '0.85rem' }}
              >
                Remove
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Bulk import ─────────────────────────────────────────────────── */}
      {showBulkModal && (
        <div
          style={{
            position: 'fixed', inset: 0, backgroundColor: 'rgba(15,23,42,0.6)',
            backdropFilter: 'blur(4px)', zIndex: 110, display: 'flex',
            alignItems: 'center', justifyContent: 'center', padding: '1rem',
          }}
          onClick={() => { if (!importing) setShowBulkModal(false); }}
        >
          <div
            onClick={(e) => e.stopPropagation()}
            style={{
              backgroundColor: 'white', borderRadius: '18px', width: '100%',
              maxWidth: '680px', border: '1px solid #E2E8F0', overflow: 'hidden',
              maxHeight: '90vh', display: 'flex', flexDirection: 'column',
            }}
          >
            <div style={{
              padding: '1.15rem 1.5rem', borderBottom: '1px solid #E2E8F0',
              display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            }}>
              <div>
                <h3 style={{ fontSize: '1.1rem', fontWeight: 800, color: '#0F172A', margin: 0, fontFamily: "'Outfit', sans-serif" }}>
                  Bulk Import Students
                </h3>
                <p style={{ fontSize: '0.78rem', color: '#64748B', margin: '2px 0 0' }}>
                  Columns: registration number, first name, last name, CNIC, programme, batch
                </p>
              </div>
              <button type="button" onClick={() => setShowBulkModal(false)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#64748B' }}>
                <X size={18} />
              </button>
            </div>

            <div style={{ padding: '1.25rem 1.5rem', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
              <DraftNotice draft={bulkDraft} online={online} onDiscard={() => { setBulkText(''); setParsed([]); }} />

              {/* Programme and batch are matched by NAME against the live
                  lookup tables, so the template is generated from those same
                  tables — its example row is guaranteed to import. */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', flexWrap: 'wrap' }}>
                <input ref={fileInputRef} type="file" accept=".csv,.tsv,.txt" onChange={handleFileUpload} style={{ fontSize: '0.8rem', flex: '1 1 220px' }} />
                <button
                  type="button"
                  onClick={downloadTemplate}
                  style={{
                    display: 'inline-flex', alignItems: 'center', gap: '6px',
                    padding: '0.45rem 0.85rem', borderRadius: '8px',
                    border: '1px solid #CBD5E1', background: 'white',
                    color: '#334155', fontWeight: 700, fontSize: '0.78rem', cursor: 'pointer',
                  }}
                  title="A CSV with the right headers and a working example row from this database"
                >
                  <Download size={14} /> Download template
                </button>
              </div>

              <div style={{
                padding: '0.6rem 0.85rem', borderRadius: '8px',
                backgroundColor: '#F5F3FF', border: '1px solid #DDD6FE',
                color: '#5B21B6', fontSize: '0.76rem', lineHeight: 1.55,
              }}>
                Each row creates a student <strong>and their login</strong>, and the
                passwords are shown once when the import finishes. Registration
                numbers from the file are kept as written; a number already in use
                rejects that row and leaves the rest alone.
              </div>

              <textarea
                value={bulkText}
                onChange={(e) => { setBulkText(e.target.value); parseRows(e.target.value); }}
                rows={8}
                placeholder={'registration_number,first_name,last_name,cnic,programme,batch\n2026-AIMS-REG-0001,Ali,Khan,12345-1234567-1,BS Computer Science,BSCS-2023'}
                style={{ ...inputStyle, fontFamily: 'monospace', fontSize: '0.78rem', resize: 'vertical' }}
              />

              {bulkError && (
                <pre style={{
                  padding: '0.6rem 0.85rem', borderRadius: '8px', backgroundColor: '#FEF2F2',
                  border: '1px solid #FECACA', color: '#991B1B', fontSize: '0.75rem',
                  whiteSpace: 'pre-wrap', margin: 0,
                }}>
                  {bulkError}
                </pre>
              )}

              {parsed.length > 0 && (
                <p style={{ fontSize: '0.82rem', color: '#065F46', margin: 0 }}>
                  {parsed.length} row{parsed.length === 1 ? '' : 's'} ready to import.
                </p>
              )}

              {importReport && (
                <div style={{
                  padding: '0.7rem 0.9rem', borderRadius: '8px', fontSize: '0.8rem',
                  backgroundColor: importReport.failures.length ? '#FEF3C7' : '#ECFDF5',
                  border: `1px solid ${importReport.failures.length ? '#FDE68A' : '#A7F3D0'}`,
                  color: importReport.failures.length ? '#92400E' : '#065F46',
                }}>
                  <strong>{importReport.saved} student{importReport.saved === 1 ? '' : 's'} admitted, with logins.</strong>
                  {importReport.failures.length > 0 && (
                    <>
                      <p style={{ margin: '6px 0 2px' }}>{importReport.failures.length} rejected:</p>
                      <ul style={{ margin: 0, paddingLeft: '1.1rem' }}>
                        {importReport.failures.slice(0, 5).map((f) => <li key={f}>{f}</li>)}
                        {importReport.failures.length > 5 && (
                          <li>…and {importReport.failures.length - 5} more</li>
                        )}
                      </ul>
                    </>
                  )}
                </div>
              )}

              {/* The one and only time these passwords are readable. They are
                  stored as bcrypt hashes, so nothing can look them up again —
                  the only remedy for a lost one is reissuing it per account.
                  Copyable as a block, because handing out forty of them one at
                  a time is how they get lost. */}
              {importReport?.issued?.length > 0 && (
                <div style={{
                  padding: '0.85rem 1rem', borderRadius: '10px',
                  backgroundColor: '#FFFBEB', border: '1px solid #FDE68A',
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '0.75rem', flexWrap: 'wrap', marginBottom: '0.6rem' }}>
                    <strong style={{ fontSize: '0.83rem', color: '#92400E' }}>
                      Sign-in details — shown once, not recoverable
                    </strong>
                    <button
                      type="button"
                      onClick={() => navigator.clipboard?.writeText(
                        importReport.issued
                          .map((s) => `${s.name}\t${s.regNo}\t${s.email}\t${s.password}`)
                          .join('\n'),
                      )}
                      style={{
                        display: 'inline-flex', alignItems: 'center', gap: '5px',
                        padding: '0.35rem 0.7rem', borderRadius: '7px',
                        border: '1px solid #FCD34D', background: 'white',
                        color: '#92400E', fontWeight: 700, fontSize: '0.75rem', cursor: 'pointer',
                      }}
                    >
                      Copy all
                    </button>
                  </div>
                  <div style={{ maxHeight: '180px', overflowY: 'auto' }}>
                    <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.74rem' }}>
                      <thead>
                        <tr style={{ textAlign: 'left', color: '#92400E' }}>
                          <th style={{ padding: '3px 6px' }}>Name</th>
                          <th style={{ padding: '3px 6px' }}>Reg. No.</th>
                          <th style={{ padding: '3px 6px' }}>Email</th>
                          <th style={{ padding: '3px 6px' }}>Password</th>
                        </tr>
                      </thead>
                      <tbody>
                        {importReport.issued.map((s) => (
                          <tr key={s.regNo || s.email} style={{ borderTop: '1px solid #FDE68A' }}>
                            <td style={{ padding: '3px 6px', color: '#0F172A', fontWeight: 600 }}>{s.name}</td>
                            <td style={{ padding: '3px 6px', color: '#475569' }}>{s.regNo}</td>
                            <td style={{ padding: '3px 6px', color: '#475569' }}>{s.email}</td>
                            <td style={{ padding: '3px 6px', fontFamily: 'monospace', color: '#0F172A' }}>{s.password}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </div>

            <div style={{
              padding: '1rem 1.5rem', borderTop: '1px solid #E2E8F0',
              display: 'flex', justifyContent: 'flex-end', gap: '0.6rem', backgroundColor: '#F8FAFC',
            }}>
              <button
                type="button"
                onClick={() => setShowBulkModal(false)}
                disabled={importing}
                style={{ padding: '0.55rem 1.1rem', borderRadius: '8px', border: '1px solid #CBD5E1', background: 'white', color: '#475569', fontWeight: 600, cursor: 'pointer', fontSize: '0.85rem' }}
              >
                Close
              </button>
              <button
                type="button"
                onClick={runImport}
                disabled={importing || !parsed.length || !online}
                style={{
                  padding: '0.55rem 1.1rem', borderRadius: '8px', border: 'none',
                  backgroundColor: importing || !parsed.length || !online ? '#CBD5E1' : '#6366F1',
                  color: 'white', fontWeight: 700, fontSize: '0.85rem',
                  cursor: importing || !parsed.length || !online ? 'not-allowed' : 'pointer',
                  display: 'flex', alignItems: 'center', gap: '6px',
                }}
              >
                {importing && <Loader2 size={14} className="loader-spin" />}
                {importing ? 'Importing…' : `Import ${parsed.length || ''}`.trim()}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* The one-time credentials popup. Rendered last so it sits above
          everything, and only closable once the admin confirms they have
          saved the passwords — see CredentialsDialog for why. */}
      <CredentialsDialog result={credentials} onClose={() => setCredentials(null)} />
    </div>
  );
}
