/*
 * Validates SQL generated by the model before it is allowed near the database.
 *
 * WHERE THIS SITS IN THE TRUST CHAIN
 * ----------------------------------
 * This is the SECOND line of defence, not the first. The first is the
 * `aims_ai_ro` account, which holds SELECT and nothing else: if every check
 * below were commented out, a generated DELETE would still be refused by the
 * server, and password hashes, CNICs, salaries and payroll would still be
 * unreadable.
 *
 * That ordering matters, because a SQL parser written in regular expressions
 * is not a SQL parser. Anyone who has tried to block statements by pattern
 * knows the list of bypasses is open-ended — comment injection, string
 * splitting, unicode escapes, dialect quirks nobody remembers. Treating this
 * file as the thing standing between a model and the data would be a mistake.
 *
 * What it is genuinely good for:
 *
 *   - catching the model's honest mistakes early, with a message it can act on
 *   - refusing statement shapes that are pointless for answering a question
 *     (multi-statement, file access) so they never reach the server at all
 *   - forcing a LIMIT, which the grants cannot do
 *   - producing an auditable record of what was attempted and why it was
 *     refused
 *
 * So: defence in depth, deliberately, with the load-bearing control in the
 * database rather than here.
 */

const config = require("../../config/assistant");

/*
 * Statement prefixes that can begin a legitimate read.
 *
 * SHOW and DESCRIBE are deliberately absent. They are read-only, but the
 * schema is supplied to the model as context rather than discovered by it,
 * and allowing schema enumeration gives an injected prompt a way to map the
 * database before asking for something from it.
 */
const ALLOWED_PREFIX = /^\s*(SELECT|WITH)\b/i;

/*
 * Constructs refused outright.
 *
 * Every one of these is either impossible under the read-only grants anyway
 * (so refusing early just produces a clearer message) or is a read that has
 * no business answering a question about students and fees.
 */
const FORBIDDEN = [
    [/\bINTO\s+(OUT|DUMP)FILE\b/i, "writing query output to a file"],
    [/\bLOAD_FILE\s*\(/i, "reading server files"],
    [/\bLOAD\s+DATA\b/i, "loading data from a file"],
    [/\binformation_schema\b/i, "reading database metadata"],
    [/\bperformance_schema\b/i, "reading server internals"],
    [/\bmysql\s*\./i, "reading the MySQL system database"],
    [/\bsys\s*\./i, "reading the sys schema"],
    [/\b(INSERT|UPDATE|DELETE|REPLACE|MERGE)\b/i, "modifying data"],
    [/\b(DROP|ALTER|CREATE|TRUNCATE|RENAME)\b/i, "changing database structure"],
    [/\b(GRANT|REVOKE|SET\s+PASSWORD)\b/i, "changing privileges"],
    [/\b(CALL|EXECUTE|PREPARE|DEALLOCATE)\b/i, "executing procedures or prepared statements"],
    [/\bLOCK\s+TABLES\b/i, "locking tables"],
    [/\bBENCHMARK\s*\(/i, "running a benchmark function"],
    [/\bSLEEP\s*\(/i, "delaying execution"],
    [/\bGET_LOCK\s*\(/i, "taking an advisory lock"],

    // The assistant's own storage: every user's transcripts, and the audit
    // trail of every query ever run through it. Also revoked at the grant
    // level; refused here so the message says why.
    [/\bassistant_(conversations|messages|query_log)\b/i,
        "reading the assistant's own conversation and audit tables"],

    // Withheld at the column level too, but a clear refusal beats a raw
    // ER_COLUMNACCESS_DENIED_ERROR surfacing to a user.
    [/\bpassword_hash\b/i, "reading password hashes"],
    [/\bcnic_bform\b/i, "reading national identity numbers"],
    [/\bbasic_salary\b/i, "reading salary information"],
    [/\bpayroll\b/i, "reading payroll"]
];

/*
 * Strips comments and string literals before the pattern checks.
 *
 * Without this, `SELECT 1 /* UPDATE * / FROM students` trips the UPDATE rule,
 * and more importantly `SELECT '-- DROP TABLE'` does too — a legitimate query
 * refused for text inside a quoted string. Removing literals first means the
 * checks look at SQL structure rather than at content the query merely
 * mentions.
 *
 * The stripped copy is used ONLY for validation. What executes is the
 * original statement.
 */
const stripLiteralsAndComments = (sql) =>
    String(sql)
        .replace(/\/\*[\s\S]*?\*\//g, " ")   // /* block comments */
        .replace(/--[^\n]*/g, " ")            // -- line comments
        .replace(/#[^\n]*/g, " ")             // # line comments
        .replace(/'(?:[^'\\]|\\.|'')*'/g, "''")   // single-quoted strings
        .replace(/"(?:[^"\\]|\\.|"")*"/g, '""');  // double-quoted strings

/*
 * Splits on semicolons that are actual statement separators.
 *
 * Run against the stripped copy, so a semicolon inside a string literal has
 * already been removed and cannot be mistaken for a separator.
 */
const statementCount = (stripped) =>
    stripped.split(";").map((s) => s.trim()).filter(Boolean).length;

/*
 * Appends or tightens a LIMIT.
 *
 * The grants cannot express "at most 500 rows", and a model that forgets a
 * LIMIT on a 60,000-row attendance table produces a result that is useless to
 * read and expensive to move. An existing smaller LIMIT is respected; a larger
 * one is reduced.
 */
const enforceLimit = (sql, max) => {

    const trimmed = String(sql).trim().replace(/;+\s*$/, "");

    // LIMIT n  or  LIMIT offset, n  or  LIMIT n OFFSET m
    const existing = trimmed.match(/\bLIMIT\s+(\d+)\s*(?:,\s*(\d+))?\s*$/i);

    if (!existing) {
        return `${trimmed} LIMIT ${max}`;
    }

    // With `LIMIT offset, count` the row count is the second number.
    const rowCount = Number(existing[2] ?? existing[1]);

    if (rowCount <= max) return trimmed;

    return trimmed.replace(/\bLIMIT\s+\d+\s*(?:,\s*\d+)?\s*$/i,
        existing[2] !== undefined
            ? `LIMIT ${existing[1]}, ${max}`
            : `LIMIT ${max}`);
};

/**
 * Validates a generated statement.
 *
 * Returns `{ ok: true, sql }` with the LIMIT-enforced statement, or
 * `{ ok: false, reason }` with a message written to be shown to the model so
 * it can correct itself, and to a person reading the audit log.
 *
 * `maxRows` overrides the configured ceiling. The two callers want genuinely
 * different things from it: the assistant caps results because they are about
 * to be spent as prompt tokens, while analytics caps them only so a runaway
 * join cannot exhaust memory on the way to the browser. Defaulting to the
 * assistant's value keeps every existing call site unchanged.
 */
const validate = (rawSql, maxRows) => {

    if (!rawSql || typeof rawSql !== "string" || !rawSql.trim()) {
        return { ok: false, reason: "No SQL was provided." };
    }

    const sql = rawSql.trim();

    if (sql.length > 5000) {
        return {
            ok: false,
            reason: "The query is unreasonably long; narrow the question instead."
        };
    }

    const stripped = stripLiteralsAndComments(sql);

    if (statementCount(stripped) > 1) {
        return {
            ok: false,
            reason:
                "Only a single statement may be run. Multiple statements " +
                "separated by semicolons are refused."
        };
    }

    if (!ALLOWED_PREFIX.test(stripped)) {
        return {
            ok: false,
            reason:
                "Only SELECT queries (optionally beginning with WITH) are " +
                "allowed. This assistant has read-only access."
        };
    }

    for (const [pattern, description] of FORBIDDEN) {
        if (pattern.test(stripped)) {
            return {
                ok: false,
                reason: `Refused: the query attempts ${description}.`
            };
        }
    }

    return {
        ok: true,
        sql: enforceLimit(sql, Number(maxRows) > 0 ? Number(maxRows) : config.maxSqlRows)
    };
};

/*
 * Every table-ish identifier the statement reads from.
 *
 * Matches what follows FROM and JOIN, which is where a table can be named. A
 * subquery's FROM is matched by the same rule, so nesting does not hide a
 * reference.
 *
 * Run against the literal-stripped copy, so a string containing the word
 * "from" is not mistaken for a clause.
 */
const referencedTables = (stripped) => {

    const names = new Set();
    const pattern = /\b(?:FROM|JOIN)\s+([A-Za-z_][A-Za-z0-9_$.]*)/gi;

    let match;

    while ((match = pattern.exec(stripped)) !== null) {
        names.add(match[1].toLowerCase());
    }

    return [...names];
};

/**
 * Validates a teacher's generated SQL.
 *
 * Everything `validate()` refuses is refused here too; this adds the three
 * conditions that make the CTE-shadowing approach in scopedSql.js sound. See
 * that file for why the scope is applied by redefining table names rather than
 * by injecting a WHERE clause.
 *
 * Returns `{ ok: true, sql }` where `sql` is the caller's statement with the
 * scoped CTE prelude prepended and a LIMIT enforced.
 */
const validateScoped = (rawSql, prelude, allowedTables, maxRows) => {

    const base = validate(rawSql, maxRows);
    if (!base.ok) return base;

    const stripped = stripLiteralsAndComments(base.sql);

    /*
     * 1. No WITH of their own.
     *
     * It would collide with the prelude, and worse, `WITH students AS (...)`
     * would redefine the very name the scoping depends on. `validate()` allows
     * WITH because an admin may legitimately use it.
     */
    if (/^\s*WITH\b/i.test(stripped)) {
        return {
            ok: false,
            reason:
                "Refused: start the query with SELECT. WITH clauses are not " +
                "available here."
        };
    }

    /*
     * 2. No schema-qualified names.
     *
     * `aims_db.students` resolves to the real table and bypasses the CTE
     * entirely, which would defeat the whole mechanism.
     */
    const qualified = referencedTables(stripped).filter((name) => name.includes("."));

    if (qualified.length) {
        return {
            ok: false,
            reason:
                `Refused: database-qualified names are not allowed ` +
                `(${qualified.join(", ")}). Use the plain table name.`
        };
    }

    /*
     * 3. Only allowlisted names.
     *
     * Any other identifier would resolve to a real base table, since only
     * these have a scoped CTE shadowing them.
     */
    const allowed = new Set(allowedTables.map((name) => name.toLowerCase()));

    const disallowed = referencedTables(stripped)
        .filter((name) => !allowed.has(name));

    if (disallowed.length) {
        return {
            ok: false,
            reason:
                `Refused: you can only query ${allowedTables.join(", ")}. ` +
                `This query referenced ${disallowed.join(", ")}, which is ` +
                `outside the data you teach.`
        };
    }

    return { ok: true, sql: `${prelude}${base.sql}`, inner: base.sql };
};

module.exports = {
    validate,
    validateScoped,
    enforceLimit,
    stripLiteralsAndComments,
    statementCount,
    referencedTables
};
