import { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Download, FileSpreadsheet, FileText, FileType2 } from 'lucide-react';
import Layout from '../../components/faculty/Layout.jsx';
import DataTable from '../../components/faculty/DataTable.jsx';
import FilterBar, { FilterSelect, FilterInput, FilterDate } from '../../components/faculty/FilterBar.jsx';
import DataGate from '../../components/faculty/DataState.jsx';
import { useAuth } from '../../context/FacultyAuthContext.jsx';
import { useToast } from '../../components/faculty/Toast.jsx';
import { faculty as facultyApi } from '../../api/endpoints';
import { useFacultyClasses } from '../../hooks/useFacultyLookups';
import { fmtDateShort } from '../../utils/helpers.js';
import { exportCSV, exportExcel, exportPDF } from '../../utils/exporters.js';
import './Reports.css';

/*
 * Every table here is generated by GET /api/faculty/reports, so the screen and
 * the export cannot disagree and a report is not limited to whatever the
 * browser happened to have downloaded. The seven tabs used to be computed in
 * the browser from `marks`, `submissions` and `fees` — collections the loader
 * left empty for a teacher — so five of them were permanently blank.
 *
 * Two are gone rather than kept as empty tables:
 *   Fee Reports        - teachers are refused the fee endpoints by design.
 *   Teacher Performance - it listed every colleague from a directory the
 *                        teacher cannot read; "Class Summary" is the same
 *                        question asked about their own classes.
 */

const REPORT_TABS = [
  { key: 'attendance', label: 'Attendance' },
  { key: 'marks', label: 'Marks' },
  { key: 'grades', label: 'Grades' },
  { key: 'assignments', label: 'Assignments & Quizzes' },
  { key: 'student-performance', label: 'Student Performance' },
  { key: 'class-summary', label: 'Class Summary' },
];

const pctBadge = (v, pass = 75) => {
  if (v === null || v === undefined) return 'badge-neutral';
  return v >= pass ? 'badge-success' : 'badge-danger';
};

const pctText = (v) => (v === null || v === undefined ? '—' : `${v}%`);

const gradeTone = (letter) => {
  if (!letter || letter === '—') return 'neutral';
  if (letter.startsWith('A')) return 'success';
  if (letter.startsWith('B')) return 'info';
  if (letter.startsWith('C') || letter.startsWith('D')) return 'warning';
  return 'danger';
};

/** Per-tab table shape and the flat rows its export writes. */
const CONFIG = {
  attendance: {
    title: 'Attendance Report',
    columns: [
      { key: 'registration_number', label: 'Roll Number' },
      { key: 'full_name', label: 'Student', render: (r) => <strong>{r.full_name}</strong> },
      { key: 'section_name', label: 'Section' },
      { key: 'subject_code', label: 'Subject' },
      { key: 'present', label: 'Present', align: 'center' },
      { key: 'absent', label: 'Absent', align: 'center' },
      { key: 'late', label: 'Late', align: 'center' },
      { key: 'leave', label: 'Leave', align: 'center' },
      { key: 'total_sessions', label: 'Sessions', align: 'center' },
      {
        key: 'percentage',
        label: 'Attendance %',
        align: 'center',
        render: (r) => <span className={`badge ${pctBadge(r.percentage)}`}>{pctText(r.percentage)}</span>,
      },
      { key: 'standing', label: 'Standing' },
    ],
    headers: ['Roll Number', 'Student', 'Section', 'Subject', 'Present', 'Absent', 'Late', 'Leave', 'Sessions', 'Attendance %', 'Standing'],
    toRow: (r) => [r.registration_number, r.full_name, r.section_name, r.subject_code, r.present, r.absent, r.late, r.leave, r.total_sessions, pctText(r.percentage), r.standing],
    empty: 'No attendance has been recorded for your classes in this period.',
    emptyAction: { label: 'Mark attendance', to: '/faculty/attendance' },
  },

  marks: {
    title: 'Marks Report',
    columns: [
      { key: 'registration_number', label: 'Roll Number' },
      { key: 'full_name', label: 'Student', render: (r) => <strong>{r.full_name}</strong> },
      { key: 'section_name', label: 'Section' },
      { key: 'subject', label: 'Subject' },
      { key: 'exam_name', label: 'Exam' },
      { key: 'exam_type', label: 'Type' },
      { key: 'obtained_marks', label: 'Marks', align: 'center' },
      { key: 'total_marks', label: 'Total', align: 'center' },
      { key: 'percentage', label: '%', align: 'center', render: (r) => pctText(r.percentage) },
      { key: 'grade', label: 'Grade', align: 'center', render: (r) => <span className={`badge badge-${gradeTone(r.grade)}`}>{r.grade}</span> },
      { key: 'status', label: 'Status' },
      { key: 'exam_date', label: 'Date', render: (r) => fmtDateShort(r.exam_date) },
    ],
    headers: ['Roll Number', 'Student', 'Section', 'Subject', 'Exam', 'Type', 'Marks', 'Total', 'Percentage', 'Grade', 'Status', 'Date'],
    toRow: (r) => [r.registration_number, r.full_name, r.section_name, r.subject, r.exam_name, r.exam_type, r.obtained_marks, r.total_marks, pctText(r.percentage), r.grade, r.status, fmtDateShort(r.exam_date)],
    empty: 'No marks have been entered against your subjects yet.',
    emptyAction: { label: 'Enter marks', to: '/faculty/marks' },
  },

  grades: {
    title: 'Grade Report',
    columns: [
      { key: 'registration_number', label: 'Roll Number' },
      { key: 'full_name', label: 'Student', render: (r) => <strong>{r.full_name}</strong> },
      { key: 'section_name', label: 'Section' },
      { key: 'exams_taken', label: 'Exams', align: 'center' },
      { key: 'obtained', label: 'Obtained', align: 'center' },
      { key: 'total', label: 'Total', align: 'center' },
      { key: 'percentage', label: 'Overall %', align: 'center', render: (r) => pctText(r.percentage) },
      { key: 'grade', label: 'Grade', align: 'center', render: (r) => <span className={`badge badge-${gradeTone(r.grade)}`}>{r.grade}</span> },
      { key: 'grade_point', label: 'Points', align: 'center', render: (r) => (r.grade_point ?? '—') },
      { key: 'result', label: 'Result', render: (r) => <span className={`badge badge-${r.result === 'Pass' ? 'success' : 'danger'}`}>{r.result}</span> },
    ],
    headers: ['Roll Number', 'Student', 'Section', 'Exams', 'Obtained', 'Total', 'Overall %', 'Grade', 'Points', 'Result'],
    toRow: (r) => [r.registration_number, r.full_name, r.section_name, r.exams_taken, r.obtained, r.total, pctText(r.percentage), r.grade, r.grade_point ?? '—', r.result],
    empty: 'Grades are computed from entered marks — none exist for your subjects yet.',
    emptyAction: { label: 'Enter marks', to: '/faculty/marks' },
  },

  assignments: {
    title: 'Assignments & Quizzes Report',
    columns: [
      { key: 'exam_name', label: 'Title', render: (r) => <strong>{r.exam_name}</strong> },
      { key: 'exam_type', label: 'Type' },
      { key: 'subject_code', label: 'Subject' },
      { key: 'section_name', label: 'Section' },
      { key: 'exam_date', label: 'Date', render: (r) => fmtDateShort(r.exam_date) },
      { key: 'total_marks', label: 'Out Of', align: 'center' },
      { key: 'students', label: 'Students', align: 'center' },
      { key: 'marked', label: 'Marked', align: 'center' },
      { key: 'pending', label: 'Pending', align: 'center' },
      { key: 'completion', label: 'Marked %', align: 'center', render: (r) => <span className={`badge ${pctBadge(r.completion, 100)}`}>{r.completion}%</span> },
      { key: 'average_percentage', label: 'Class Avg', align: 'center', render: (r) => pctText(r.average_percentage) },
    ],
    headers: ['Title', 'Type', 'Subject', 'Section', 'Date', 'Out Of', 'Students', 'Marked', 'Pending', 'Marked %', 'Class Avg'],
    toRow: (r) => [r.exam_name, r.exam_type, r.subject_code, r.section_name, fmtDateShort(r.exam_date), r.total_marks, r.students, r.marked, r.pending, `${r.completion}%`, pctText(r.average_percentage)],
    // This report reads `exams` rows of type Assignment / Quiz / Practical.
    // The institute has only ever recorded Mid-Term and Final exams, so an
    // empty table here means "none have been set", not "nothing loaded" — and
    // the generic message could not tell the two apart.
    empty: 'No assignments, quizzes or practicals have been set for your subjects yet. '
      + 'Create one from Marks → New Exam and it will appear here.',
    emptyAction: { label: 'Go to Marks', to: '/faculty/marks' },
  },

  'student-performance': {
    title: 'Student Performance Report',
    columns: [
      { key: 'registration_number', label: 'Roll Number' },
      { key: 'full_name', label: 'Student', render: (r) => <strong>{r.full_name}</strong> },
      { key: 'section_name', label: 'Section' },
      { key: 'program_name', label: 'Program' },
      { key: 'semester_number', label: 'Semester', align: 'center', render: (r) => (r.semester_number ?? '—') },
      { key: 'attendance_percentage', label: 'Attendance', align: 'center', render: (r) => <span className={`badge ${pctBadge(r.attendance_percentage)}`}>{pctText(r.attendance_percentage)}</span> },
      { key: 'marks_percentage', label: 'Marks', align: 'center', render: (r) => pctText(r.marks_percentage) },
      { key: 'exams_taken', label: 'Exams', align: 'center' },
      { key: 'cgpa', label: 'CGPA', align: 'center', render: (r) => (r.cgpa != null ? r.cgpa.toFixed(2) : '—') },
      { key: 'grade', label: 'Grade', align: 'center', render: (r) => <span className={`badge badge-${gradeTone(r.grade)}`}>{r.grade}</span> },
      { key: 'tier', label: 'Tier', render: (r) => <span className={`badge ${r.tier === 'Good' ? 'badge-success' : r.tier === 'Average' ? 'badge-warning' : r.tier === 'At Risk' ? 'badge-danger' : 'badge-neutral'}`}>{r.tier}</span> },
    ],
    headers: ['Roll Number', 'Student', 'Section', 'Program', 'Semester', 'Attendance %', 'Marks %', 'Exams', 'CGPA', 'Grade', 'Tier'],
    toRow: (r) => [r.registration_number, r.full_name, r.section_name, r.program_name, r.semester_number ?? '—', pctText(r.attendance_percentage), pctText(r.marks_percentage), r.exams_taken, r.cgpa ?? '—', r.grade, r.tier],
  },

  'class-summary': {
    title: 'Class Summary Report',
    columns: [
      { key: 'subject_code', label: 'Subject', render: (r) => <strong>{r.subject_code}</strong> },
      { key: 'subject_name', label: 'Title' },
      { key: 'section_name', label: 'Section' },
      { key: 'program_name', label: 'Program' },
      { key: 'semester_number', label: 'Semester', align: 'center', render: (r) => (r.semester_number ?? '—') },
      { key: 'credit_hours', label: 'Credits', align: 'center' },
      { key: 'students', label: 'Students', align: 'center' },
      { key: 'weekly_slots', label: 'Slots/Week', align: 'center' },
      { key: 'attendance_percentage', label: 'Attendance', align: 'center', render: (r) => <span className={`badge ${pctBadge(r.attendance_percentage)}`}>{pctText(r.attendance_percentage)}</span> },
      { key: 'graded_students', label: 'Graded', align: 'center' },
      { key: 'marks_percentage', label: 'Class Avg', align: 'center', render: (r) => pctText(r.marks_percentage) },
      { key: 'class_grade', label: 'Grade', align: 'center', render: (r) => <span className={`badge badge-${gradeTone(r.class_grade)}`}>{r.class_grade}</span> },
    ],
    headers: ['Subject', 'Title', 'Section', 'Program', 'Semester', 'Credits', 'Students', 'Slots/Week', 'Attendance %', 'Graded', 'Class Avg', 'Grade'],
    toRow: (r) => [r.subject_code, r.subject_name, r.section_name, r.program_name, r.semester_number ?? '—', r.credit_hours, r.students, r.weekly_slots, pctText(r.attendance_percentage), r.graded_students, pctText(r.marks_percentage), r.class_grade],
  },
};

export default function Reports() {
  const showToast = useToast();
  const navigate = useNavigate();
  const { can } = useAuth();

  const [tab, setTab] = useState('attendance');
  // Shared with My Classes, Attendance and Marks — one request between them.
  const { data: classes } = useFacultyClasses();
  const [classKey, setClassKey] = useState('all');
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');
  const [query, setQuery] = useState('');
  const [exporting, setExporting] = useState('');

  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const selectedClass = useMemo(
    () => classes.find((c) => c.key === classKey) || null,
    [classes, classKey],
  );

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await facultyApi.report({
        type: tab,
        subject_id: selectedClass?.subject_id,
        section_id: selectedClass?.section_id,
        date_from: tab === 'attendance' ? dateFrom : undefined,
        date_to: tab === 'attendance' ? dateTo : undefined,
      });
      setReport(res?.data || null);
    } catch (err) {
      setError(err.message || 'Could not generate this report.');
      setReport(null);
    } finally {
      setLoading(false);
    }
  }, [tab, selectedClass, dateFrom, dateTo]);

  useEffect(() => { load(); }, [load]);

  const active = CONFIG[tab];

  // Search is applied to the generated rows rather than sent to the server:
  // the report is already scoped to this teacher, so this is only narrowing.
  const rows = useMemo(() => {
    const all = report?.rows || [];
    const q = query.trim().toLowerCase();
    if (!q) return all;
    return all.filter((r) => Object.values(r).some(
      (v) => v !== null && v !== undefined && String(v).toLowerCase().includes(q),
    ));
  }, [report, query]);

  const handleExport = (format) => {
    if (!rows.length) {
      showToast('There is nothing to export in this report.');
      return;
    }

    setExporting(format);
    const filename = `${active.title.replace(/\s+/g, '_').toLowerCase()}.`;
    const exportRows = rows.map(active.toRow);

    const scope = report?.scope;
    const subtitle = [
      report?.teacher ? `Teacher: ${report.teacher}` : null,
      scope?.classes?.length ? `Classes: ${scope.classes.join(', ')}` : null,
      scope?.date_from || scope?.date_to
        ? `Period: ${scope.date_from ? fmtDateShort(scope.date_from) : 'start'} – ${scope.date_to ? fmtDateShort(scope.date_to) : 'today'}`
        : null,
      `${exportRows.length} records`,
      report?.generated_at ? `Generated ${new Date(report.generated_at).toLocaleString()}` : null,
    ].filter(Boolean).join(' · ');

    setTimeout(() => {
      if (format === 'csv') exportCSV(`${filename}csv`, active.headers, exportRows);
      if (format === 'xlsx') exportExcel(`${filename}xlsx`, active.title, active.headers, exportRows);
      if (format === 'pdf') {
        exportPDF(`${filename}pdf`, {
          title: active.title,
          subtitle,
          headers: active.headers,
          rows: exportRows,
        });
      }
      setExporting('');
      showToast(`${active.title} exported as ${format.toUpperCase()}`);
    }, 200);
  };

  if (!can('view_reports')) {
    return (
      <Layout title="Reports">
        <div className="empty-state">You do not have permission to view reports.</div>
      </Layout>
    );
  }

  return (
    <Layout title="Reports">
      <div className="reports-head">
        <div>
          <h2>Reports</h2>
          <p>
            Attendance · Marks · Grades · Assignments · Performance · Class Summary —
            generated from your own classes and exportable to Excel, PDF or CSV
          </p>
        </div>
        <div className="attendance-export-group">
          <button className="btn btn-outline" disabled={exporting === 'xlsx' || loading} onClick={() => handleExport('xlsx')}>
            <FileSpreadsheet size={14} /> {exporting === 'xlsx' ? 'Exporting…' : 'Excel'}
          </button>
          <button className="btn btn-outline" disabled={exporting === 'pdf' || loading} onClick={() => handleExport('pdf')}>
            <FileText size={14} /> {exporting === 'pdf' ? 'Exporting…' : 'PDF'}
          </button>
          <button className="btn btn-outline" disabled={exporting === 'csv' || loading} onClick={() => handleExport('csv')}>
            <FileType2 size={14} /> {exporting === 'csv' ? 'Exporting…' : 'CSV'}
          </button>
        </div>
      </div>

      <div className="reports-tabs">
        {REPORT_TABS.map((t) => (
          <button
            key={t.key}
            className={`reports-tab${tab === t.key ? ' active' : ''}`}
            onClick={() => setTab(t.key)}
          >
            {t.label}
          </button>
        ))}
      </div>

      <FilterBar
        resetActive={classKey !== 'all' || !!query || !!dateFrom || !!dateTo}
        onReset={() => { setClassKey('all'); setQuery(''); setDateFrom(''); setDateTo(''); }}
      >
        <FilterInput label="Search" placeholder="Any field in this report" value={query} onChange={(e) => setQuery(e.target.value)} />
        <FilterSelect
          label="Class"
          value={classKey}
          onChange={(e) => setClassKey(e.target.value)}
          allLabel="All My Classes"
          options={classes.map((c) => ({
            value: c.key,
            label: `${c.subject_code} · Sec ${c.section_name}`,
          }))}
        />
        {tab === 'attendance' && (
          <>
            <FilterDate label="Date From" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} />
            <FilterDate label="Date To" value={dateTo} onChange={(e) => setDateTo(e.target.value)} />
          </>
        )}
      </FilterBar>

      <div className="reports-count">
        {loading ? 'Generating…' : `${rows.length} records`}
        {report?.scope?.classes?.length ? ` · ${report.scope.classes.join(', ')}` : ''}
        {' · '}
        <Download size={12} style={{ verticalAlign: -1 }} /> Export to Excel, PDF or CSV
      </div>

      <DataGate loading={loading} error={error} onRetry={load} label="Generating report…">
        {/* A report with no rows because the underlying records do not exist
            reads identically to one that failed to load, so the reason is
            spelled out with the action that would fill it. A search that
            matched nothing is a different case and keeps the plain message. */}
        {rows.length === 0 && !query && active.empty ? (
          <div className="empty-state">
            <p style={{ margin: 0 }}>{active.empty}</p>
            {active.emptyAction && (
              <button
                type="button"
                className="btn btn-outline"
                style={{ marginTop: '0.9rem' }}
                onClick={() => navigate(active.emptyAction.to)}
              >
                {active.emptyAction.label}
              </button>
            )}
          </div>
        ) : (
          <DataTable
            columns={active.columns}
            rows={rows}
            rowKey="id"
            searchable={false}
            emptyMessage="No records match your search in this report."
          />
        )}
      </DataGate>
    </Layout>
  );
}
