/*
 * Notification emission.
 *
 * WHY THIS EXISTS
 * ---------------
 * `notifications` was a read-only table. Every portal had a Notifications page,
 * a bell and an unread badge reading from it, and nothing in the entire backend
 * ever wrote a row — a grep for `Notification.create`, `bulkCreate` and
 * `INSERT INTO notifications` returned nothing. The only rows present came from
 * a database dump and were all dated 2024, which is why a teacher opening the
 * page landed on "You're all caught up" and an admin saw a single read notice
 * from January. The screens were correct; the table had simply stopped growing.
 *
 * This module is the missing half. Controllers call it at the moment an event
 * actually happens, and it works out who is affected and what each of them
 * should read.
 *
 * WHY IT IS NOT PART OF auditService
 * ----------------------------------
 * The two look similar and are opposites in the way that matters: the audit
 * trail records ONE row describing the ACTOR ("admin #7 published this
 * result"), kept forever, readable only by administrators. A notification is N
 * rows addressed to the people AFFECTED ("your result is out") — never the
 * actor — dismissible, and scoped to each recipient's own account. Deriving one
 * from the other would force whichever came second to distort: audit rows have
 * no recipient list, and notification rows must not name the staff member who
 * caused them.
 *
 * WHY IT IS NOT ANNOUNCEMENTS EITHER
 * ----------------------------------
 * An announcement is one row broadcast to a role, authored by a person, with no
 * per-reader state; it lives on the Announcements screen. A notification is
 * addressed to one account, generated by an event, and carries `is_read`. They
 * are deliberately kept in separate tables behind separate screens, so nothing
 * here ever emits an announcement and nothing here reads one.
 *
 * FAILURE BEHAVIOUR
 * -----------------
 * Emitting never throws and never blocks the act it describes, for the same
 * reason auditService.record() doesn't: refusing to publish a result because
 * the notifications table was locked would be a far worse outcome than a
 * missing notice. Errors go to the console and the caller proceeds. Callers
 * should therefore NOT await this inside a transaction that the act depends on.
 */

const { sequelize } = require("../database/connection");
const Notification = require("../models/notification.model");
const { ROLES } = require("../config/roles");

const SELECT = { type: sequelize.QueryTypes.SELECT };

/*
 * The categories a notification may carry.
 *
 * The first twelve are the values already present in the database, kept so the
 * rows written from today read alongside the historical ones and so the
 * per-user "mute this category" setting keeps working for anyone who had
 * already set it. ACCOUNT and EXAM are new: credential and timetable events had
 * been landing under the catch-all `Academic`, which made them impossible to
 * mute separately and impossible to give a distinct icon.
 *
 * There is deliberately no ANNOUNCEMENT member — see the header.
 */
const TYPES = {
    FEE: "Fee",
    ATTENDANCE: "Attendance",
    RESULT: "Result",
    EXAM: "Exam",
    ACADEMIC: "Academic",
    REGISTRATION: "Registration",
    DOCUMENT: "Document",
    ACCOUNT: "Account",
    SCHOLARSHIP: "Scholarship",
    LIBRARY: "Library",
    LEAVE: "Leave",
    PAYROLL: "Payroll",
    HR: "HR",
    MEETING: "Meeting"
};

/*
 * Drives the tone each portal renders. Decided here rather than mapped from
 * `type` on the client, because the category alone cannot tell them apart: an
 * attendance row is routine when a register is filed and urgent when the same
 * student crosses below 75%, and both are type Attendance.
 */
const PRIORITY = {
    LOW: "low",
    NORMAL: "normal",
    HIGH: "high"
};

/*
 * Where each portal answers a given subject.
 *
 * The same event reaches people in different portals, and the route that shows
 * it differs for each — a fee notice opens /student/fee-management for the
 * student and the Fees tab of the parent dashboard for their guardian. Holding
 * the four routes together per subject is what stops a link being written for
 * the emitter's own portal and 404ing for everyone else.
 *
 * The parent portal used to be a single route with internal tab state, so its
 * links carried `?tab=`. It has a route per module now, so they name the route
 * directly. The rows already in `notifications` still carry the old shape and
 * are NOT migrated: /parent-dashboard is kept as a redirect that translates
 * ?tab=, and the portal's own parentLinkToPath() reads both. A data migration
 * to rewrite historical rows would be all risk and no gain.
 */
const LINKS = {
    fees: {
        [ROLES.STUDENT]: "/student/fee-management",
        [ROLES.PARENT]: "/parent/fees",
        [ROLES.ADMIN]: "/fee-management",
        [ROLES.SUPER_ADMIN]: "/fee-management",
        [ROLES.ACCOUNTANT]: "/fee-management"
    },
    results: {
        [ROLES.STUDENT]: "/student/result",
        [ROLES.PARENT]: "/parent/results",
        [ROLES.TEACHER]: "/faculty/marks",
        [ROLES.ADMIN]: "/examination",
        [ROLES.SUPER_ADMIN]: "/examination"
    },
    attendance: {
        [ROLES.STUDENT]: "/student/attendance",
        [ROLES.PARENT]: "/parent/attendance",
        [ROLES.TEACHER]: "/faculty/attendance",
        [ROLES.ADMIN]: "/attendance",
        [ROLES.SUPER_ADMIN]: "/attendance"
    },
    exams: {
        [ROLES.STUDENT]: "/student/my-courses",
        [ROLES.PARENT]: "/parent/results",
        [ROLES.TEACHER]: "/faculty/my-classes",
        [ROLES.ADMIN]: "/examination",
        [ROLES.SUPER_ADMIN]: "/examination"
    },
    timetable: {
        [ROLES.STUDENT]: "/student/time-table",
        [ROLES.PARENT]: "/parent/timetable",
        [ROLES.TEACHER]: "/faculty/timetable"
    },
    documents: {
        [ROLES.STUDENT]: "/student/document",
        [ROLES.ADMIN]: "/students",
        [ROLES.SUPER_ADMIN]: "/students"
    },
    courses: {
        [ROLES.STUDENT]: "/student/my-courses",
        [ROLES.TEACHER]: "/faculty/my-classes",
        [ROLES.ADMIN]: "/enrollment",
        [ROLES.SUPER_ADMIN]: "/enrollment"
    },
    profile: {
        [ROLES.STUDENT]: "/student/profile",
        [ROLES.PARENT]: "/parent/profile",
        [ROLES.TEACHER]: "/faculty/profile",
        [ROLES.ADMIN]: "/settings",
        [ROLES.SUPER_ADMIN]: "/settings"
    },
    // Credential events. Everyone has a change-password screen at one shared
    // route, so this subject is role-independent.
    account: {
        [ROLES.STUDENT]: "/change-password",
        [ROLES.PARENT]: "/change-password",
        [ROLES.TEACHER]: "/change-password",
        [ROLES.ADMIN]: "/change-password",
        [ROLES.SUPER_ADMIN]: "/change-password",
        [ROLES.HR]: "/change-password",
        [ROLES.ACCOUNTANT]: "/change-password",
        [ROLES.LIBRARY]: "/change-password"
    },
    people: {
        [ROLES.ADMIN]: "/user-management",
        [ROLES.SUPER_ADMIN]: "/user-management"
    }
};

// ---------------------------------------------------------------- audiences

/*
 * Every account that should hear about something happening to one student:
 * the student's own login, plus each linked guardian.
 *
 * `students.user_id` is nullable — a student admitted before their account was
 * provisioned has none — and a guardian link may point at a soft-deleted
 * parent, so both are filtered here rather than producing rows addressed to
 * nobody. Deactivated and deleted users are excluded for the same reason:
 * a notification for an account that cannot sign in is never read and still
 * counts against the unread badge of nobody.
 *
 * The student's name rides along on both branches. A guardian's copy has to be
 * worded in the third person ("Ali's result is out", not "your result"), and
 * carrying the name on a join the query is already doing is cheaper than every
 * caller looking it up separately just to phrase one sentence.
 */
const studentAudience = async (studentId) => {
    if (!studentId) return [];

    return sequelize.query(
        `SELECT u.user_id, u.role_id, s.first_name, s.last_name
           FROM students s
           JOIN users u ON u.user_id = s.user_id
          WHERE s.student_id = :studentId
            AND s.is_deleted = 0
            AND u.is_active = 1
            AND u.is_deleted = 0

          UNION

         SELECT u.user_id, u.role_id, s.first_name, s.last_name
           FROM student_guardians sg
           JOIN students s ON s.student_id = sg.student_id
           JOIN parents p ON p.parent_id = sg.parent_id
           JOIN users u ON u.user_id = p.user_id
          WHERE sg.student_id = :studentId
            AND s.is_deleted = 0
            AND p.is_deleted = 0
            AND u.is_active = 1
            AND u.is_deleted = 0`,
        { ...SELECT, replacements: { studentId } }
    );
};

/** The student's own account only — used where a guardian has no stake. */
const studentOnlyAudience = async (studentId) => {
    if (!studentId) return [];

    return sequelize.query(
        `SELECT u.user_id, u.role_id, s.first_name, s.last_name
           FROM students s
           JOIN users u ON u.user_id = s.user_id
          WHERE s.student_id = :studentId
            AND s.is_deleted = 0
            AND u.is_active = 1
            AND u.is_deleted = 0`,
        { ...SELECT, replacements: { studentId } }
    );
};

/*
 * A teacher's login. `teachers` holds no user_id of its own — the person is an
 * `employees` row and the account hangs off that — so this is a two-hop join
 * and not the one-liner it looks like it should be.
 */
const teacherAudience = async (teacherId) => {
    if (!teacherId) return [];

    return sequelize.query(
        `SELECT u.user_id, u.role_id
           FROM teachers t
           JOIN employees e ON e.employee_id = t.employee_id
           JOIN users u ON u.user_id = e.user_id
          WHERE t.teacher_id = :teacherId
            AND t.is_deleted = 0
            AND e.is_deleted = 0
            AND u.is_active = 1
            AND u.is_deleted = 0`,
        { ...SELECT, replacements: { teacherId } }
    );
};

/** One named account, by user id. */
const userAudience = async (userId) => {
    if (!userId) return [];

    return sequelize.query(
        `SELECT user_id, role_id
           FROM users
          WHERE user_id = :userId
            AND is_active = 1
            AND is_deleted = 0`,
        { ...SELECT, replacements: { userId } }
    );
};

/*
 * Staff who need to act on something.
 *
 * Defaults to administrators. Fee events pass the accountant role as well,
 * because a payment a parent has declared sits unverified until someone in the
 * accounts office looks at it, and they are the ones who do.
 */
const staffAudience = async (roleIds = [ROLES.SUPER_ADMIN, ROLES.ADMIN]) => {
    if (!roleIds.length) return [];

    return sequelize.query(
        `SELECT user_id, role_id
           FROM users
          WHERE role_id IN (:roleIds)
            AND is_active = 1
            AND is_deleted = 0`,
        { ...SELECT, replacements: { roleIds } }
    );
};

/*
 * Every student currently taking a subject, plus their guardians.
 *
 * Used for events that belong to a class rather than a person — an exam being
 * scheduled, a timetable slot moving. Restricted to Active enrolments so a
 * student who dropped the subject is not told about its exam.
 */
const subjectAudience = async (subjectId, semesterId) => {
    if (!subjectId) return [];

    const semesterClause = semesterId ? "AND e.semester_id = :semesterId" : "";

    return sequelize.query(
        `SELECT u.user_id, u.role_id
           FROM enrollments e
           JOIN students s ON s.student_id = e.student_id
           JOIN users u ON u.user_id = s.user_id
          WHERE e.subject_id = :subjectId
            ${semesterClause}
            AND e.status = 'Active'
            AND s.is_deleted = 0
            AND u.is_active = 1
            AND u.is_deleted = 0

          UNION

         SELECT u.user_id, u.role_id
           FROM enrollments e
           JOIN student_guardians sg ON sg.student_id = e.student_id
           JOIN parents p ON p.parent_id = sg.parent_id
           JOIN users u ON u.user_id = p.user_id
          WHERE e.subject_id = :subjectId
            ${semesterClause}
            AND e.status = 'Active'
            AND p.is_deleted = 0
            AND u.is_active = 1
            AND u.is_deleted = 0`,
        { ...SELECT, replacements: { subjectId, semesterId } }
    );
};

// ------------------------------------------------------------------- emit

/*
 * Resolves a per-recipient field.
 *
 * Wording usually has to differ by role even though the event is one event:
 * the student reads "Your result for Spring 2024 has been published" and their
 * father reads "Ali's result for Spring 2024 has been published". Passing a
 * function keeps both versions of that sentence at the call site, next to each
 * other, instead of in two separate emit() calls that can drift apart.
 */
const resolve = (value, role, context) => (
    typeof value === "function" ? value(role, context) : value
);

/**
 * Writes one notification per recipient.
 *
 * Never throws. Returns the number of rows written, which is only useful for
 * logging — no caller should branch on it.
 *
 * @param {object}   spec
 * @param {Array}    spec.audience  [{ user_id, role_id }] — from the resolvers above
 * @param {string}   spec.type      one of TYPES
 * @param {string|fn} spec.title    heading; a function receives the role id
 * @param {string|fn} spec.message  body; a function receives the role id
 * @param {string}   [spec.subject] key into LINKS, resolved per recipient role
 * @param {string|fn} [spec.link]   explicit route, overriding `subject`
 * @param {string}   [spec.priority] one of PRIORITY, default NORMAL
 * @param {number}   [spec.actorUserId] the person who caused it — never notified
 */
const emit = async ({
    audience = [],
    type,
    title,
    message,
    subject,
    link,
    priority = PRIORITY.NORMAL,
    actorUserId = null
}) => {
    try {
        if (!type || !title || !message) {
            console.warn("[notify] incomplete notification was not emitted", { type, title });
            return 0;
        }

        /*
         * Two things happen here and both matter.
         *
         * Dedupe: a parent with two children in the same class, or a teacher who
         * is also the guardian of a student, appears in an audience twice. The
         * UNION queries above already dedupe within themselves, but a caller may
         * concatenate two audiences.
         *
         * Actor removal: the person who performed the act must not be told about
         * it. Without this an admin who records a payment gets "a payment has
         * been recorded" a second later, and a teacher marking their own
         * register is notified that they marked it. That is the single fastest
         * way to train people to ignore the bell.
         */
        const seen = new Set();
        const recipients = [];

        for (const row of audience) {
            const userId = row?.user_id;
            if (!userId || userId === actorUserId || seen.has(userId)) continue;
            seen.add(userId);
            recipients.push(row);
        }

        if (!recipients.length) return 0;

        const now = new Date();

        const rows = recipients.map((row) => {
            const role = row.role_id;
            const resolvedLink = link !== undefined
                ? resolve(link, role)
                : (subject ? LINKS[subject]?.[role] ?? null : null);

            return {
                user_id: row.user_id,
                type,
                // The columns are VARCHAR(120)/(255); a long subject name or a
                // free-text reason could otherwise fail the whole insert and
                // lose every recipient's row, not just the oversized one.
                title: String(resolve(title, role)).slice(0, 120),
                message: String(resolve(message, role)).slice(0, 255),
                link: resolvedLink ? String(resolvedLink).slice(0, 255) : null,
                priority,
                is_read: false,
                created_at: now
            };
        });

        await Notification.bulkCreate(rows);

        return rows.length;

    } catch (error) {
        // Deliberately swallowed — see the header. A missing notification must
        // never fail the admission, payment or publication that triggered it.
        console.error("[notify] emission failed:", error.message);
        return 0;
    }
};

/*
 * The common shape: tell a student and their guardians about something, with
 * the guardian's copy worded in the third person.
 *
 * The caller supplies both sentences already built, because it is holding the
 * student row and the subject name anyway — resolving them here would add a
 * lookup per event for data the call site already has.
 */
const notifyStudent = async ({
    studentId,
    includeGuardians = true,
    type,
    title,
    ownMessage,
    guardianMessage,
    subject,
    priority,
    actorUserId
}) => {
    const audience = includeGuardians
        ? await studentAudience(studentId)
        : await studentOnlyAudience(studentId);

    // Carried on every row of the audience query; taken from the first because
    // they all describe the same student.
    const name = audience.length
        ? [audience[0].first_name, audience[0].last_name].filter(Boolean).join(" ")
        : "";

    // Guardians of a student whose name did not resolve still need a readable
    // sentence, so the third-person wording falls back to a generic noun rather
    // than rendering an empty possessive.
    const who = name || "your child";

    return emit({
        audience,
        type,
        title: (role) => resolve(title, role, who),
        message: (role) => (
            role === ROLES.PARENT && guardianMessage
                ? resolve(guardianMessage, role, who)
                : resolve(ownMessage, role, who)
        ),
        subject,
        priority,
        actorUserId
    });
};

module.exports = {
    TYPES,
    PRIORITY,
    LINKS,
    emit,
    notifyStudent,
    studentAudience,
    studentOnlyAudience,
    teacherAudience,
    userAudience,
    staffAudience,
    subjectAudience
};
